// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Spanish Castilian (`es`).
class AppLocalizationsEs extends AppLocalizations {
  AppLocalizationsEs([String locale = 'es']) : super(locale);

  @override
  String get appTitle => 'Desquadra';

  @override
  String get drawerFastAccess => 'ACCESO RÁPIDO';

  @override
  String get drawerDashboard => 'Panel';

  @override
  String get drawerTransactions => 'Transacciones';

  @override
  String get drawerBudgets => 'Presupuestos';

  @override
  String get drawerMonthSummary => 'Resumen por Categorías';

  @override
  String get drawerManagement => 'GESTIÓN';

  @override
  String get drawerCategories => 'Categorías';

  @override
  String get drawerAccounts => 'Cuentas';

  @override
  String get drawerSettings => 'AJUSTES';

  @override
  String get drawerAccount => 'CUENTA';

  @override
  String get drawerLogout => 'Cerrar Sesión';

  @override
  String get settingsTitle => 'Ajustes';

  @override
  String get settingsManageShortcutTitle => 'Gestionar';

  @override
  String get settingsManageShortcutDesc => 'Categorías, Cuentas, Metas';

  @override
  String get settingsManageShortcutButton => 'Abrir menú';

  @override
  String get drawerDebts => 'Deudas';

  @override
  String get drawerGoals => 'Metas';

  @override
  String get drawerRecurring => 'Cuentas fijas';

  @override
  String get settingsPreferences => 'Preferencias';

  @override
  String get settingsMainCurrency => 'Moneda principal';

  @override
  String get settingsMainCurrencyDesc =>
      'El Resumen del mes usa solo esta moneda. Otras monedas aparecen en las cuentas (sin conversión).';

  @override
  String get settingsAutomation => 'Automatización';

  @override
  String get settingsAutoGenerate => 'Generar automáticamente';

  @override
  String get settingsAutoGenerateDesc =>
      'Crea entradas recurrentes al inicio del mes (no mueve dinero).';

  @override
  String get settingsAutoGenerateInfo =>
      'Las transacciones se crearán como pendientes en la fecha prevista.';

  @override
  String get settingsVersion => 'Versión';

  @override
  String get commonCancel => 'Cancelar';

  @override
  String get commonSave => 'Guardar';

  @override
  String get currencyOther => 'Otra';

  @override
  String get currencyCustomLabel => 'Código (ej. COP)';

  @override
  String get currencyCustomHint => '3-5 letras mayúsculas';

  @override
  String get currencyInvalid => 'Código inválido. Use 3-5 letras (A-Z).';

  @override
  String get settingsAccountSection => 'Cuenta';

  @override
  String get successSettingsUpdate => '¡Configuración guardada con éxito!';

  @override
  String errorSettingsUpdate(String error) {
    return 'Error al actualizar configuración: $error';
  }

  @override
  String settingsVersionValue(String version) {
    return 'Versión $version';
  }

  @override
  String get appTagline => 'Finanzas simples, sin complicaciones.';

  @override
  String drawerMainCurrency(String currency) {
    return 'Moneda principal: $currency';
  }

  @override
  String get settingsLanguage => 'Idioma';

  @override
  String get languageEnglish => 'Inglés';

  @override
  String get languagePortuguese => 'Portugués';

  @override
  String get languageSpanish => 'Español';

  @override
  String get onboardingFeature1 => '• Registrar gasto en 3 toques';

  @override
  String get onboardingFeature2 => '• Ver saldo real y planeado';

  @override
  String get onboardingFeature3 => '• Todo en un solo lugar, sin jerga';

  @override
  String get onboardingStartFast => 'Empezar rápido';

  @override
  String get commonSkip => 'Saltar';

  @override
  String get onboardingWelcome => '¡Bienvenido!';

  @override
  String get onboardingDescription =>
      'Vamos a dejar todo listo en menos de 60 segundos.';

  @override
  String get onboardingUseExamples => 'Quiero usar ejemplos';

  @override
  String get onboardingSkipDescription => 'Puedes saltar y ajustar después.';

  @override
  String get onboardingCreateAccount =>
      'Crearemos una cuenta para que registres gastos.';

  @override
  String get onboardingChooseCreation => 'Elige qué quieres crear ahora.';

  @override
  String get onboardingCreateBudget => 'Crear presupuesto base';

  @override
  String get onboardingCreateBudgetDesc => 'Podrás editar después.';

  @override
  String get onboardingFirstTransaction =>
      'Ya puedes registrar tu primer gasto.';

  @override
  String get onboardingAddCards =>
      'Añade tus tarjetas para controlar facturas.';

  @override
  String get commonDelete => 'Eliminar';

  @override
  String get transactionTypeExpense => 'Gasto';

  @override
  String get transactionTypeIncome => 'Ingreso';

  @override
  String get commonActive => 'Activa';

  @override
  String get recurringTitle => 'Recurrencias';

  @override
  String get recurringMyRules => 'Mis reglas';

  @override
  String get recurringOpenPlanner => 'Abrir planificador';

  @override
  String recurringPendingItems(int count) {
    return 'Tienes $count ítems por confirmar.';
  }

  @override
  String get commonView => 'Ver';

  @override
  String get commonEdit => 'Editar';

  @override
  String get recurringPlanMonth => 'Planear Mes';

  @override
  String get recurringGeneratedEntries => 'Entradas generadas';

  @override
  String get commonBack => 'Volver';

  @override
  String get commonNext => 'Siguiente';

  @override
  String get commonFinish => 'Finalizar';

  @override
  String get onboardingMainAccount => 'Cuenta principal';

  @override
  String get accountNameLabel => 'Nombre de la cuenta';

  @override
  String get accountTypeLabel => 'Tipo';

  @override
  String get accountTypeBank => 'Banco';

  @override
  String get accountTypeCash => 'Efectivo';

  @override
  String get accountTypeWallet => 'Cartera';

  @override
  String get onboardingBaseCategories => 'Categorías base';

  @override
  String get onboardingAllSet => 'Todo listo';

  @override
  String get onboardingExamplesCreated =>
      'Creamos ejemplos básicos para que ajustes después.';

  @override
  String get onboardingMinimumCreated => 'Creamos lo mínimo para que empieces.';

  @override
  String get onboardingCreditCards => 'Tarjetas de crédito';

  @override
  String get onboardingCardName => 'Nombre de la tarjeta';

  @override
  String get onboardingNoCards =>
      'Ninguna tarjeta añadida. Clic en + para añadir o Siguiente para saltar.';

  @override
  String get recurringAppDescription => 'La app solo registra. No cobra.';

  @override
  String get commonNew => 'Nueva';

  @override
  String get recurringInactive => 'Inactivas';

  @override
  String get recurringNewRule => 'Nueva recurrencia';

  @override
  String get recurringEmptyState =>
      'Crea una recurrencia para planear tu mes en segundos.';

  @override
  String recurringFrequencyMonthly(int day) {
    return 'Cada mes el día $day';
  }

  @override
  String get recurringFrequencyWeekly => 'Semanal';

  @override
  String get recurringFrequencyYearly => 'Anual';

  @override
  String get commonComingSoon => 'Próximamente';

  @override
  String get commonPause => 'Pausar';

  @override
  String get commonActivate => 'Activar';

  @override
  String get recurringDeleteTitle => '¿Eliminar regla?';

  @override
  String get recurringDeleteDesc => 'Esto no elimina entradas ya generadas.';

  @override
  String get recurringPlanMonthDesc =>
      'Genera las entradas del mes a partir de las reglas.';

  @override
  String get recurringPendingConfirmation => 'Confirmación pendiente';

  @override
  String recurringGeneratedSuccess(int count) {
    return '¡Generadas $count entradas!';
  }

  @override
  String recurringGeneratedDialogBody(int count) {
    return '$count entradas fueron creadas como pendientes.';
  }

  @override
  String get commonStay => 'Quedarse aquí';

  @override
  String get recurringGoToConfirm => 'Ir a confirmar';

  @override
  String get commonErrorGenerating => 'Error al generar';

  @override
  String get recurringNonePlanned =>
      'Ninguna recurrencia prevista para este mes.';

  @override
  String recurringGenerateButton(int count) {
    return 'Generar entradas ($count)';
  }

  @override
  String get recurringStatusToGenerate => 'Por generar';

  @override
  String get recurringStatusGenerated => 'Generadas';

  @override
  String get recurringStatusIgnored => 'Ignoradas';

  @override
  String get commonNoDescription => 'Sin descripción';

  @override
  String get recurringChipGenerated => 'Generado';

  @override
  String get recurringRestoreTooltip => 'Restaurar (Incluir en generación)';

  @override
  String get recurringIgnoreTooltip => 'Ignorar (No generar)';

  @override
  String recurringMissingGenerated(int count) {
    return 'Faltan $count entradas por generar';
  }

  @override
  String get recurringViewPending => 'Ver pendientes';

  @override
  String get recurringViewRules => 'Ver reglas';

  @override
  String get recurringNoRulesYet => 'Aún no tienes recurrencias';

  @override
  String get recurringCreateFirst => 'Crear primera';

  @override
  String get categoriesActive => 'Categorías activas';

  @override
  String get categoriesDeleteTitle => '¿Eliminar categoría?';

  @override
  String get categoriesDeleteDesc =>
      'Esto eliminará la categoría y todas las transacciones vinculadas. No se puede deshacer.';

  @override
  String get categoriesDeleted => 'Categoría eliminada';

  @override
  String get categoriesNew => 'Nueva categoría';

  @override
  String get categoriesEdit => 'Editar categoría';

  @override
  String get commonPreview => 'Vista previa';

  @override
  String get commonName => 'Nombre';

  @override
  String get categoriesParent => 'Categoría padre';

  @override
  String get categoriesNoParent => 'Sin padre';

  @override
  String get categoriesColor => 'Color';

  @override
  String get categoriesIcon => 'Icono';

  @override
  String get commonNameRequired => 'Nombre obligatorio';

  @override
  String get dashboardMainAccounts => 'Cuentas principales';

  @override
  String get dashboardMainAccountsDesc => 'Las que más usas en el día a día';

  @override
  String get dashboardMainAccountsInfoTitle => 'Cuentas principales';

  @override
  String get dashboardMainAccountsInfoBody =>
      'Mostramos las cuentas con más movimientos este mes.';

  @override
  String get transactionsManageFixed => 'Gestionar gastos fijos';

  @override
  String get transactionsPendingTitle => 'Transacciones pendientes';

  @override
  String get transactionsGroup => 'Agrupar por:';

  @override
  String get transactionsGroupCategory => 'Categoría';

  @override
  String get transactionsGroupRecurrence => 'Recurrencia';

  @override
  String get transactionsFilterAllAccounts => 'Todas las cuentas';

  @override
  String get transactionsFilterAllCategories => 'Todas las categorías';

  @override
  String get transactionsFilterAllStatus => 'Todos';

  @override
  String get transactionsFilterPending => 'Pendiente';

  @override
  String get transactionsFilterConfirmed => 'Confirmado';

  @override
  String get transactionsDeleteTitle => '¿Eliminar transacción?';

  @override
  String get transactionsDeleteDesc => 'Esta acción no se puede deshacer.';

  @override
  String get transactionsConfirmAll => 'Confirmar todo';

  @override
  String get transactionsLabelAccount => 'Cuenta';

  @override
  String get transactionsLabelCategory => 'Categoría';

  @override
  String get transactionsLabelStatus => 'Estado';

  @override
  String get transactionsLabelEntryAccount => 'Cuenta de Entrada';

  @override
  String get transactionsLabelCategoryOptional => 'Categoría (Opcional)';

  @override
  String get transactionsLabelSource => 'De (Origen)';

  @override
  String get transactionTypeTransfer => 'Transferencia';

  @override
  String get transactionFormTitleNew => 'Nueva Transacción';

  @override
  String get transactionFormTitleEdit => 'Editar Transacción';

  @override
  String get transactionFormLabelDate => 'Fecha';

  @override
  String get transactionFormLabelNote => 'Nota';

  @override
  String get transactionFormLabelTags => 'Etiquetas (separadas por coma)';

  @override
  String get transactionFormSave => 'Guardar';

  @override
  String get transactionFormErrorSave => 'Error al guardar';

  @override
  String get transactionFormSuccessSave => '¡Transacción guardada!';

  @override
  String get transactionFormConfirmDelete => '¿Eliminar transacción?';

  @override
  String get transactionFormConfirmConversion => 'Confirmar conversión';

  @override
  String get transactionFormLabelYouSend => 'Envías:';

  @override
  String get transactionFormLabelYouReceive => 'Recibes:';

  @override
  String transactionFormEffectiveRate(
    String fromCurrency,
    String toCurrency,
    String rate,
  ) {
    return 'Tasa efectiva: 1 $fromCurrency ≈ $toCurrency $rate';
  }

  @override
  String get transactionFormChangeAccountTitle => '¿Cambiar cuentas?';

  @override
  String get transactionFormChangeAccountDesc =>
      'Esto puede cambiar la moneda y limpiar los valores.';

  @override
  String get transactionFormChangeAccountConfirm => 'Cambiar y limpiar';

  @override
  String get transactionFormTypeExpense => 'Gasto';

  @override
  String get transactionFormTypeIncome => 'Ingreso';

  @override
  String get transactionFormTypeTransfer => 'Transf.';

  @override
  String get transactionFormMsgRecurringError =>
      'Transacción guardada, pero no se pudo crear la recurrencia.';

  @override
  String get transactionFormMsgRecurringSuccess =>
      '¡Transacción guardada y recurrencia creada!';

  @override
  String get transactionFormRecurringConfirm => 'Confirmar recurrente';

  @override
  String get commonConfirm => 'Confirmar';

  @override
  String get commonContinue => 'Continuar';

  @override
  String get accountsTitle => 'Cuentas';

  @override
  String get accountsWarningCurrency => 'Monedas necesitan revisión';

  @override
  String get accountsWarningCurrencyDesc =>
      'Algunas cuentas tienen moneda inválida y pueden causar valores erróneos en el tablero.';

  @override
  String get accountsFixCurrency => 'Corregir ahora';

  @override
  String get accountsActive => 'Cuentas activas';

  @override
  String get accountsCardsSection => 'Tarjetas';

  @override
  String get accountsCardChip => 'TARJETA';

  @override
  String get accountsCardCurrentBill => 'Factura actual';

  @override
  String get accountsCardViewDebts => 'Ver en Deudas';

  @override
  String get accountsDeleteTitle => '¿Eliminar cuenta?';

  @override
  String get accountsDeleteDesc =>
      'Esto eliminará la cuenta y todas las transacciones vinculadas. No se puede deshacer.';

  @override
  String get accountsDeleted => 'Cuenta eliminada';

  @override
  String get accountsNew => 'Nueva cuenta';

  @override
  String get accountsEdit => 'Editar cuenta';

  @override
  String get accountsTypeMoney => 'Efectivo';

  @override
  String get accountsTypeBank => 'Banco';

  @override
  String get accountsTypeWallet => 'Billetera';

  @override
  String get accountsTypeBroker => 'Inversiones';

  @override
  String get accountsTypeCard => 'Tarjeta de Crédito';

  @override
  String get accountsLabelBank => 'Banco';

  @override
  String get accountsLabelCurrency => 'Moneda';

  @override
  String get accountsLabelCurrencyCode => 'Código de moneda';

  @override
  String get accountsHintCurrencyCode => 'Ej: COP, ARS';

  @override
  String get accountsHelperCurrencyCode =>
      'Usa 3-5 letras mayúsculas. Ej: COP.';

  @override
  String get accountsErrorCurrencyInvalid =>
      'Código inválido. Usa 3-5 letras (ej: COP).';

  @override
  String get budgetsTitle => 'Presupuestos';

  @override
  String get budgetsTabGoals => 'Metas';

  @override
  String get budgetsTabFixed => 'Gastos Fijos';

  @override
  String get budgetsMonthTitle => 'Presupuesto del mes';

  @override
  String get budgetsPlanPeriod => 'Plan del período';

  @override
  String get budgetsLabelPlanned => 'Planeado';

  @override
  String get budgetsLabelActual => 'Actual';

  @override
  String get budgetsLabelRemaining => 'Restante';

  @override
  String get budgetsHeaderIncome => 'Ingresos planeados';

  @override
  String get budgetsHeaderExpense => 'Gastos planeados';

  @override
  String get budgetsHeaderBalance => 'Saldo planeado';

  @override
  String get budgetsEmptyTitle => 'Sin presupuesto para este mes';

  @override
  String get budgetsEmptyDesc =>
      'Crea un presupuesto para planificar tus gastos por categoría.';

  @override
  String get budgetsCreateButton => 'Crear presupuesto para este mes';

  @override
  String get budgetsActionRemove => 'Remover del mes';

  @override
  String get budgetsSuccessRemoved =>
      'Categoría eliminada del presupuesto de este mes';

  @override
  String get budgetsRemoveCategory => 'Remover del mes';

  @override
  String get budgetsSaveButton => 'Guardar Presupuesto';

  @override
  String get budgetsSuccessSaved => '¡Presupuesto guardado!';

  @override
  String get budgetsMonthSummaryTitle => 'Resumen del mes';

  @override
  String get budgetsMonthSummaryPlannedCategories =>
      'Gastos planificados (categorías)';

  @override
  String get budgetsMonthSummaryPlannedDebts => 'Pagos de deudas planificados';

  @override
  String get budgetsMonthSummaryTotalOutflow => 'Total de salidas planificadas';

  @override
  String get budgetsMonthSummaryOtherCurrencies =>
      'Otras monedas (sin conversión)';

  @override
  String get budgetsDebtPlannedTitle => 'Deudas (pagos planificados)';

  @override
  String get budgetsDebtPlannedSubtitle =>
      'Reserva cuánto vas a pagar este mes. No es un gasto nuevo.';

  @override
  String get budgetsDebtPaymentNote =>
      'Pagar deuda no es un gasto nuevo. Es pagar algo que ya debes.';

  @override
  String get budgetsDebtPayLabel => 'Voy a pagar';

  @override
  String get budgetsDebtOweLabel => 'Debo';

  @override
  String budgetsDebtPaidPlanned(Object paid, Object planned) {
    return 'Pagado: $paid / $planned planificado';
  }

  @override
  String get budgetsDebtActionZeroAll => 'Poner todo en 0';

  @override
  String get budgetsDebtActionSuggest => 'Sugerir pagos';

  @override
  String budgetsDebtOverpaid(Object amount) {
    return 'Pagaste $amount más de lo planificado.';
  }

  @override
  String budgetsDebtRemaining(Object amount) {
    return 'Faltan $amount para tu plan.';
  }

  @override
  String get budgetsDebtEmptyState => 'No tienes deudas activas.';

  @override
  String get budgetsDebtMinimumWarning => 'Tu plan está por debajo del mínimo.';

  @override
  String budgetsDebtTotalPlannedLabel(Object currency) {
    return 'Total pagos planificados ($currency)';
  }

  @override
  String get budgetsCategoriesTitle => 'Gastos por categoría';

  @override
  String get accountsSuccessCurrencyFixed => '¡Monedas corregidas con éxito!';

  @override
  String get goalsTitle => 'Metas';

  @override
  String get goalsMyGoals => 'Tus metas';

  @override
  String get goalsNew => 'Nueva meta';

  @override
  String get goalsEdit => 'Editar meta';

  @override
  String get goalsCreate => 'Crear meta';

  @override
  String get goalsNameLabel => 'Nombre de la meta';

  @override
  String get goalsNameHint => 'Ej: Fondo de emergencia';

  @override
  String get goalsTargetAmount => 'Monto objetivo';

  @override
  String get goalsDetailsOptional => 'Detalles (opcional)';

  @override
  String get goalsTargetDate => 'Fecha objetivo (opcional)';

  @override
  String get goalsNoDate => 'Sin fecha';

  @override
  String goalsSuggestedMonthly(Object amount) {
    return 'Sugerido: $amount por mes';
  }

  @override
  String get goalsMonthlyContribution => 'Aporte mensual (opcional)';

  @override
  String get goalsLinkedAccount => 'Cuenta vinculada (opcional)';

  @override
  String get goalsContributionTitle => 'Registrar aporte';

  @override
  String get goalsContributionValue => 'Valor';

  @override
  String get goalsNoAccounts => 'No tienes cuentas activas.';

  @override
  String get goalsDate => 'Fecha';

  @override
  String get goalsNoteOptional => 'Nota (opcional)';

  @override
  String get goalsErrorName => 'Nombre obligatorio';

  @override
  String get goalsErrorAmount => 'El monto debe ser mayor a 0';

  @override
  String get goalsQuickAddConfigError =>
      'Configura un aporte mensual para usar aporte rápido';

  @override
  String get goalsAccountConfigError =>
      'Configura una cuenta para usar aporte rápido';

  @override
  String goalsContributionSuccess(Object amount) {
    return 'Aporte de $amount registrado';
  }

  @override
  String goalsProjectionIdeal(Object amount, Object date) {
    return 'Guardando $amount/mes, llegas el $date.';
  }

  @override
  String goalsProjectionOnTrack(Object amount, Object date) {
    return 'Guardando $amount/mes, llegas el $date.';
  }

  @override
  String goalsProjectionOnTrackNoDate(Object amount) {
    return 'Guardando $amount/mes';
  }

  @override
  String goalsProjectionOffTrack(Object amount, Object date) {
    return 'Para llegar el $date, necesitas guardar $amount/mes.';
  }

  @override
  String goalsProjectionDateOnly(Object date) {
    return 'Meta $date';
  }

  @override
  String goalsRemaining(Object amount) {
    return 'Restante $amount';
  }

  @override
  String get goalsQuickAdd => 'Aporte rápido';

  @override
  String get goalsCustomize => 'Personalizar';

  @override
  String get goalsViewDetails => 'Ver detalles';

  @override
  String get debtsTitle => 'Deudas';

  @override
  String get debtsActiveLiabilities => 'Pasivos activos';

  @override
  String get debtsNew => 'Nueva deuda';

  @override
  String get debtsEdit => 'Editar deuda';

  @override
  String get debtsName => 'Nombre';

  @override
  String get debtsType => 'Tipo';

  @override
  String get debtsTypeCreditCard => 'Tarjeta de Crédito';

  @override
  String get debtsTypeLoan => 'Préstamo';

  @override
  String get debtsTypeOther => 'Otro';

  @override
  String get debtsNoCreditCardAccount =>
      'No tienes cuentas tipo \'Tarjeta de Crédito\'.';

  @override
  String get debtsCreateCardAccount => 'Crear cuenta Tarjeta ahora';

  @override
  String get debtsLinkedAccount =>
      'Cuenta de la tarjeta (Donde caen las compras)';

  @override
  String get debtsInitialBalance => 'Saldo inicial';

  @override
  String get debtsInitialBalanceCurrent => 'Saldo actual (Opcional)';

  @override
  String get debtsInitialBalanceHelper =>
      'Si ya tienes saldo por pagar, ingrésalo. Si no, deja 0.';

  @override
  String get debtsInitialBalanceWarning =>
      'El saldo inicial no se puede cambiar. Ajusta registrando compra/pago.';

  @override
  String get debtsNoPayingAccount =>
      'Sin cuentas bancarias/efectivo para pagar la factura.';

  @override
  String get debtsPayingAccount => 'Cuenta pagadora por defecto (Opcional)';

  @override
  String get debtsPayingAccountHelper => 'Cuenta sugerida al pagar la factura.';

  @override
  String get debtsDueDate => 'Día de vencimiento';

  @override
  String get debtsDueDateHint => 'Ej: 10';

  @override
  String get debtsDueDateError => 'Entre 1 y 31';

  @override
  String get debtsAdvanced => 'Avanzado (Opcional)';

  @override
  String get debtsMinimumPayment => 'Pago mínimo';

  @override
  String get debtsInterestRate => 'Tasa anual (%)';

  @override
  String get debtsErrorSelectAccount => 'Selecciona la cuenta de la tarjeta';

  @override
  String get debtsErrorNoLinkedAccount =>
      'Esta deuda no tiene cuenta vinculada. Edita para vincular una cuenta Tarjeta.';

  @override
  String get debtsQuickAccountTitle => 'Crear Cuenta Rápida';

  @override
  String get debtsQuickAccountName => 'Nombre de la cuenta';

  @override
  String debtsDueDayLabel(Object day) {
    return 'Vence el día $day';
  }

  @override
  String get debtsCurrentBill => 'Factura actual:';

  @override
  String get debtsAvailableCredit => 'Crédito disponible:';

  @override
  String get debtsAllPaid => 'Todo pagado 🎉';

  @override
  String get debtsActionCharge => 'Registrar Compra';

  @override
  String get debtsActionPay => 'Pagar Factura';

  @override
  String get debtsDialogPaidTitle => 'Todo pagado ✅';

  @override
  String get debtsDialogPaidBody => 'No tienes saldo por pagar.';

  @override
  String get debtsDialogPaidAction => 'Pagar de todos modos';

  @override
  String get debtsDialogLinkTitle => 'Cuenta no vinculada';

  @override
  String get debtsDialogLinkBody =>
      'Para pagar la factura, necesitas vincular una cuenta \'Tarjeta de Crédito\'.';

  @override
  String get debtsDialogLinkAction => 'Vincular ahora';

  @override
  String get monthSummaryTitle => 'Resumen general del mes';

  @override
  String get monthSummaryTabCategories => 'Por categoría';

  @override
  String get monthSummaryTabAccounts => 'Por cuenta';

  @override
  String get monthSummaryTabOtherCurrencies => 'Otras monedas';

  @override
  String get monthSummaryHeaderHelper =>
      'Sin conversión automática. Valores por moneda.';

  @override
  String monthSummaryEmptyPrimary(Object currency) {
    return 'Sin movimientos en $currency este mes.';
  }

  @override
  String get monthSummarySeeOtherCurrencies => 'Ver en Otras monedas';

  @override
  String monthSummaryTotalSpent(Object currency) {
    return 'Total gastado ($currency):';
  }

  @override
  String get monthSummaryOtherCurrencies => 'Otras monedas (sin conversión):';

  @override
  String get monthSummaryNoAccounts => 'Ninguna cuenta encontrada';

  @override
  String get monthSummaryIncome => 'Entradas';

  @override
  String get monthSummaryPayments => 'Pagos';

  @override
  String get monthSummaryExpenses => 'Salidas';

  @override
  String get monthSummaryPurchases => 'Compras';

  @override
  String get monthSummaryNetMonth => 'Variación mensual';

  @override
  String get monthSummaryBalanceMonth => 'Saldo mensual';

  @override
  String get monthSummaryViewInvoice => 'Ver factura/historial';

  @override
  String get monthSummaryViewTransactions => 'Ver transacciones';

  @override
  String get monthSummaryNoOtherCurrencies => 'Ninguna otra moneda movida';

  @override
  String get monthSummaryOtherCurrenciesSubtitle =>
      'Los valores abajo no se convierten a la moneda principal.';

  @override
  String get monthSummaryNet => 'Neto';

  @override
  String get authLoginTitle => 'Entrar';

  @override
  String get authContinueGoogle => 'Continuar con Google';

  @override
  String get authContinueApple => 'Continuar con Apple';

  @override
  String get authOr => 'o';

  @override
  String get authLoginEmail => 'Entrar con email';

  @override
  String get authEmailLabel => 'Email';

  @override
  String get authPasswordLabel => 'Contraseña';

  @override
  String get authButtonLogin => 'Entrar';

  @override
  String get authButtonRegister => 'Crear cuenta';

  @override
  String get authLoadingLogin => 'Entrando...';

  @override
  String get authLoadingRegister => 'Creando cuenta...';

  @override
  String get authSwitchToLogin => 'Ya tengo cuenta';

  @override
  String get authSwitchToRegister => 'Crear nueva cuenta';

  @override
  String get authDisclaimer => 'Usamos tu login solo para acceder a tu cuenta.';

  @override
  String get authRegisterTitle => 'Crear cuenta';

  @override
  String get authRegisterQuick => 'Registro rápido';

  @override
  String get authRegisterSubtitle => 'Solo email y contraseña. < 30s.';

  @override
  String get transactionFormErrorCreate => 'Error al guardar la transacción.';

  @override
  String get transactionFormSuccessUpdate =>
      '¡Transacción actualizada con éxito!';

  @override
  String transactionFormErrorUpdate(String error) {
    return 'Error al guardar: $error';
  }

  @override
  String get transactionFormLabelCardPurchase => 'Compra con Tarjeta';

  @override
  String get transactionFormLabelSource => 'Cuenta de Origen';

  @override
  String get transactionsLabelDestination => 'Para (Destino)';

  @override
  String get transactionsActionImportCsv => 'Importar CSV';

  @override
  String get transactionFormRecurringError =>
      'Transacción guardada, pero no se pudo crear la recurrencia.';

  @override
  String get transactionFormRecurringSuccess =>
      '¡Transacción guardada y recurrencia creada!';

  @override
  String recurringSummaryDay(Object day) {
    return 'Mensualmente el día $day';
  }

  @override
  String get navDashboard => 'Inicio';

  @override
  String get navTransactions => 'Transacciones';

  @override
  String get navBudgets => 'Presupuestos';

  @override
  String get navSettings => 'Ajustes';

  @override
  String get dashboardShortcutTitle => 'Resumen Mensual por Categoría';

  @override
  String get dashboardShortcutDesc =>
      'Sin autoconversión.\nToca para ver gastos por moneda y categoría.';

  @override
  String get dashboardQuickActionsTitle => 'Acciones Rápidas';

  @override
  String get dashboardQuickActionExpense => 'Gasto';

  @override
  String get dashboardQuickActionIncome => 'Ingreso';

  @override
  String get dashboardQuickActionTransfer => 'Transferencia';

  @override
  String get dashboardQuickActionFixed => 'Gastos Fijos';

  @override
  String get cardLabelCredit => 'TARJETA';

  @override
  String get cardLabelBalancePay => 'Saldo a Pagar';

  @override
  String cardLabelDueDay(Object day) {
    return 'Vence el día $day';
  }

  @override
  String get cardLabelPayments => 'Pagos';

  @override
  String get cardLabelPurchases => 'Compras';

  @override
  String get cardLabelIncomes => 'Ingresos';

  @override
  String get cardLabelExpenses => 'Gastos';

  @override
  String get cardLabelMonthBalance => 'Saldo del Mes';

  @override
  String get cardLabelNoMovements => 'Sin movimientos este mes';

  @override
  String get cardActionView => 'Ver transacciones';

  @override
  String get debtsSectionTitle => 'Deudas';

  @override
  String get debtsEmptyState => 'No has registrado deudas.';

  @override
  String get debtsActionAdd => 'Añadir Deuda';

  @override
  String get debtsActionViewAll => 'Ver Deudas';

  @override
  String get debtsPaidMonth => 'Pagado este mes: ';

  @override
  String get debtsTotalToPay => 'Total a pagar';

  @override
  String debtsNextDue(Object date, Object name) {
    return 'Próximo: $date — $name';
  }

  @override
  String get debtsPaymentDisclaimer =>
      'Registra un pago (no es un cobro automático).';

  @override
  String get commonUnderstood => 'Entendido';

  @override
  String get dashboardOtherAccountsTitle => 'Otras cuentas';

  @override
  String get dashboardOtherAccountsDesc =>
      'Cuentas menos usadas o sin movimientos este mes';

  @override
  String get dashboardOtherAccountsNoMovements => 'Sin movimientos este mes';

  @override
  String dashboardOtherAccountsMonthBalance(Object amount) {
    return 'Saldo del mes: $amount';
  }

  @override
  String dashboardOtherAccountsViewAll(Object count) {
    return 'Ver todas ($count)';
  }

  @override
  String get transactionFormLabelInvoicePayment => 'Pago de Factura';

  @override
  String get transactionFormLabelCardSourceError =>
      'La tarjeta no puede ser cuenta de origen. Usa tu cuenta bancaria.';

  @override
  String get transactionFormLabelDebtWarning =>
      'Esto aumenta tu deuda. No sale del banco ahora.';

  @override
  String get transactionFormLabelPaymentValue => 'Valor del Pago';

  @override
  String get transactionFormHelperPayment =>
      'Sale del banco y se abona a la factura.';

  @override
  String get transactionFormLabelTransferValue => 'Valor';

  @override
  String get transactionFormHelperTransfer =>
      'Valor que sale del origen y entra al destino.';

  @override
  String transactionFormLabelSentValue(String currency) {
    return 'Envías ($currency)';
  }

  @override
  String get transactionFormHelperSent =>
      'Valor que sale de la cuenta de origen.';

  @override
  String transactionFormLabelReceivedValue(String currency) {
    return 'Recibes ($currency)';
  }

  @override
  String get transactionFormHelperReceived =>
      'Valor que entra en la cuenta de destino.';

  @override
  String get transactionFormLabelSelectSourceDest =>
      'Seleccionar Origen y Destino';

  @override
  String get transactionFormHelperSelectSourceDest =>
      'Elige cuentas para liberar el valor.';

  @override
  String get transactionFormLabelAlreadyCleared => '¿Ya se hizo efectivo?';

  @override
  String get transactionFormStatusCleared => 'Confirmado';

  @override
  String get transactionFormStatusPending => 'Pendiente';

  @override
  String get transactionFormHelperStatus =>
      'Si está pendiente, puedes cambiarlo después.';

  @override
  String get transactionFormLabelMoreOptions => 'Más opciones';

  @override
  String get transactionFormLabelMoreOptionsSubtitle =>
      'Nota, Etiquetas, Recurrencia';

  @override
  String get transactionFormLabelMoreOptionsRecurring => 'Recurrente';

  @override
  String get transactionFormLabelRepeat => 'Repetir automáticamente';

  @override
  String get transactionFormHelperRepeat =>
      'Crea un gasto fijo para no olvidar.';

  @override
  String get transactionFormLabelFrequencyMonthly => 'Mensual';

  @override
  String get transactionFormLabelFrequencyWeekly => 'Semanal';

  @override
  String get transactionFormActionManageFixed => 'Gestionar gastos fijos';

  @override
  String get transactionFormLabelSaveTemplate => 'Guardar como Plantilla';

  @override
  String get transactionFormLabelTemplateName => 'Nombre de la Plantilla';

  @override
  String get transactionFormActionSaving => 'Guardando...';

  @override
  String get transactionFormValidationSameAccount =>
      'Selecciona cuentas diferentes.';

  @override
  String get transactionFormCategoryPurchase => 'Categoría de Compra';

  @override
  String get transactionFormInvoiceSource => 'Tarjeta (Factura)';

  @override
  String get transactionFormPaymentSuccess => '¡Pago de factura registrado!';

  @override
  String transactionFormPaymentError(String error) {
    return 'Error al registrar pago: $error';
  }

  @override
  String get transactionFormChargeSuccess => '¡Compra registrada!';

  @override
  String transactionFormChargeError(String error) {
    return 'Error al guardar compra: $error';
  }

  @override
  String get commonToday => 'Hoy';

  @override
  String get commonYesterday => 'Ayer';

  @override
  String get commonFrom => 'de';

  @override
  String get commonTo => 'a';

  @override
  String get commonNoAccount => 'Sin cuenta';

  @override
  String get transactionsEmptyState => 'No se encontraron transacciones';

  @override
  String get onboardingPreferencesTitle => 'Preferencias';

  @override
  String get onboardingPreferencesDesc =>
      'Elige cómo quieres ver la app. Puedes cambiarlo después.';

  @override
  String get onboardingFieldLanguage => 'Idioma';

  @override
  String get onboardingFieldCurrency => 'Moneda principal';

  @override
  String get onboardingCreateAccountTitle => 'Crea tu primera cuenta';

  @override
  String get onboardingCreateAccountDesc =>
      'Ej.: banco, efectivo, billetera. Puedes agregar más después.';

  @override
  String get onboardingFieldInitialBalance => 'Saldo inicial (opcional)';

  @override
  String get onboardingHelperInitialBalance =>
      'Si no lo sabes ahora, déjalo en blanco.';

  @override
  String get onboardingErrorNoAccount =>
      'Crea al menos 1 cuenta para continuar.';

  @override
  String get onboardingCategoriesTitle => 'Elige tus categorías';

  @override
  String get onboardingCategoriesDesc =>
      'Deja marcado lo que usas. Puedes cambiarlo después.';

  @override
  String get onboardingActionSelectAll => 'Marcar todo';

  @override
  String get onboardingActionDeselectAll => 'Desmarcar todo';

  @override
  String get catHousing => 'Vivienda (alquiler/condominio)';

  @override
  String get catUtilities => 'Servicios del hogar (agua, luz, gas)';

  @override
  String get catInternet => 'Internet y celular';

  @override
  String get catGroceries => 'Supermercado';

  @override
  String get catRestaurants => 'Restaurantes';

  @override
  String get catTransport => 'Transporte y Combustible';

  @override
  String get catFuel => 'Combustible';

  @override
  String get catCarMaintenance => 'Mantenimiento del auto';

  @override
  String get catHealth => 'Salud y Farmacia';

  @override
  String get catPharmacy => 'Farmacia';

  @override
  String get catEducation => 'Educación (escuela/cursos)';

  @override
  String get catCreditCard => 'Tarjeta de crédito (gastos)';

  @override
  String get catDebts => 'Préstamos';

  @override
  String get catFees => 'Comisiones y cargos';

  @override
  String get catSubscriptions => 'Suscripciones (streaming/apps)';

  @override
  String get catPersonal => 'Cuidado personal';

  @override
  String get catClothing => 'Ropa';

  @override
  String get catWork => 'Trabajo (herramientas/servicios)';

  @override
  String get catTaxes => 'Impuestos';
}
