// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Portuguese (`pt`).
class AppLocalizationsPt extends AppLocalizations {
  AppLocalizationsPt([String locale = 'pt']) : super(locale);

  @override
  String get appTitle => 'Desquadra';

  @override
  String get drawerFastAccess => 'ACESSO RÁPIDO';

  @override
  String get drawerDashboard => 'Dashboard';

  @override
  String get drawerTransactions => 'Transações';

  @override
  String get drawerBudgets => 'Orçamentos';

  @override
  String get drawerMonthSummary => 'Resumo do mês por categorias';

  @override
  String get drawerManagement => 'GESTÃO';

  @override
  String get drawerCategories => 'Categorias';

  @override
  String get drawerAccounts => 'Contas';

  @override
  String get drawerSettings => 'AJUSTES';

  @override
  String get drawerAccount => 'CONTA';

  @override
  String get drawerLogout => 'Sair';

  @override
  String get settingsTitle => 'Ajustes';

  @override
  String get settingsManageShortcutTitle => 'Gerenciar';

  @override
  String get settingsManageShortcutDesc => 'Categorias, Contas, Metas';

  @override
  String get settingsManageShortcutButton => 'Abrir menu';

  @override
  String get drawerDebts => 'Dívidas';

  @override
  String get drawerGoals => 'Metas';

  @override
  String get drawerRecurring => 'Contas fixas';

  @override
  String get settingsPreferences => 'Preferências';

  @override
  String get settingsMainCurrency => 'Moeda principal';

  @override
  String get settingsMainCurrencyDesc =>
      'O Resumo do mês usa apenas esta moeda. Outras moedas aparecem nas contas (sem conversão).';

  @override
  String get settingsCountry => 'País';

  @override
  String get settingsCountryDesc =>
      'Usamos seu país para mostrar bancos relevantes.';

  @override
  String get settingsCountryPlaceholder => 'Selecione seu país';

  @override
  String get settingsAutomation => 'Automação';

  @override
  String get settingsAutoGenerate => 'Gerar automaticamente';

  @override
  String get settingsAutoGenerateDesc =>
      'Cria lançamentos de contas fixas ao iniciar o mês (não movimenta dinheiro).';

  @override
  String get settingsAutoGenerateInfo =>
      'As transações serão criadas como pendentes na data prevista.';

  @override
  String get settingsVersion => 'Versão';

  @override
  String get commonCancel => 'Cancelar';

  @override
  String get commonSave => 'Salvar';

  @override
  String get currencyOther => 'Outra';

  @override
  String get currencyCustomLabel => 'Código (ex: COP)';

  @override
  String get currencyCustomHint => '3-5 letras maiúsculas';

  @override
  String get currencyInvalid => 'Código inválido. Use 3 a 5 letras (A-Z).';

  @override
  String get settingsAccountSection => 'Conta';

  @override
  String get successSettingsUpdate => 'Configuração salva com sucesso!';

  @override
  String errorSettingsUpdate(String error) {
    return 'Erro ao atualizar configuração: $error';
  }

  @override
  String settingsVersionValue(String version) {
    return 'Versão $version';
  }

  @override
  String get appTagline => 'Finanças simples, sem complicação.';

  @override
  String drawerMainCurrency(String currency) {
    return 'Moeda principal: $currency';
  }

  @override
  String get settingsLanguage => 'Idioma';

  @override
  String get languageEnglish => 'Inglês';

  @override
  String get languagePortuguese => 'Português';

  @override
  String get languageSpanish => 'Espanhol';

  @override
  String get onboardingFeature1 => '• Registrar gasto em 3 toques';

  @override
  String get onboardingFeature2 => '• Ver saldo real e planejado';

  @override
  String get onboardingFeature3 => '• Tudo em um só lugar, sem jargão';

  @override
  String get onboardingStartFast => 'Começar rápido';

  @override
  String get commonSkip => 'Pular';

  @override
  String get onboardingWelcome => 'Bem-vindo!';

  @override
  String get onboardingDescription =>
      'Vamos deixar tudo pronto em menos de 60 segundos.';

  @override
  String get onboardingUseExamples => 'Quero usar exemplos';

  @override
  String get onboardingSkipDescription => 'Você pode pular e ajustar depois.';

  @override
  String get onboardingCreateAccount =>
      'Criaremos uma conta para você registrar gastos.';

  @override
  String get onboardingChooseCreation => 'Escolha o que quer criar agora.';

  @override
  String get onboardingCreateBudget => 'Criar orçamento base';

  @override
  String get onboardingCreateBudgetDesc => 'Você poderá editar depois.';

  @override
  String get onboardingFirstTransaction =>
      'Você já pode registrar seu primeiro gasto.';

  @override
  String get onboardingAddCards =>
      'Adicione seus cartões para controlar faturas.';

  @override
  String get commonDelete => 'Excluir';

  @override
  String get transactionTypeExpense => 'Despesa';

  @override
  String get transactionTypeIncome => 'Receita';

  @override
  String get commonActive => 'Ativa';

  @override
  String get recurringTitle => 'Recorrências';

  @override
  String get recurringMyRules => 'Minhas regras';

  @override
  String get recurringOpenPlanner => 'Abrir planejador';

  @override
  String recurringPendingItems(int count) {
    return 'Você tem $count itens para confirmar.';
  }

  @override
  String get commonView => 'Ver';

  @override
  String get commonEdit => 'Editar';

  @override
  String get recurringPlanMonth => 'Planejar Mês';

  @override
  String get recurringGeneratedEntries => 'Lançamentos gerados';

  @override
  String get commonBack => 'Voltar';

  @override
  String get commonNext => 'Próximo';

  @override
  String get commonFinish => 'Finalizar';

  @override
  String get onboardingMainAccount => 'Conta principal';

  @override
  String get accountNameLabel => 'Nome da conta';

  @override
  String get accountTypeLabel => 'Tipo';

  @override
  String get accountTypeBank => 'Banco';

  @override
  String get accountTypeCash => 'Dinheiro';

  @override
  String get accountTypeWallet => 'Carteira';

  @override
  String get onboardingBaseCategories => 'Categorias base';

  @override
  String get onboardingAllSet => 'Tudo pronto';

  @override
  String get onboardingExamplesCreated =>
      'Criamos exemplos básicos para você ajustar depois.';

  @override
  String get onboardingMinimumCreated => 'Criamos o mínimo para você começar.';

  @override
  String get onboardingCreditCards => 'Cartões de crédito';

  @override
  String get onboardingCardName => 'Nome do cartão';

  @override
  String get onboardingNoCards =>
      'Nenhum cartão adicionado. Clique em + para adicionar ou Próximo para pular.';

  @override
  String get recurringAppDescription => 'O app só registra. Não cobra.';

  @override
  String get commonNew => 'Nova';

  @override
  String get recurringInactive => 'Inativas';

  @override
  String get recurringNewRule => 'Nova recorrência';

  @override
  String get recurringEmptyState =>
      'Crie uma recorrência para planejar seu mês em segundos.';

  @override
  String recurringFrequencyMonthly(int day) {
    return 'Todo mês dia $day';
  }

  @override
  String get recurringFrequencyWeekly => 'Semanal';

  @override
  String get recurringFrequencyYearly => 'Anual';

  @override
  String get commonComingSoon => 'Em breve';

  @override
  String get commonPause => 'Pausar';

  @override
  String get commonActivate => 'Ativar';

  @override
  String get recurringDeleteTitle => 'Excluir regra?';

  @override
  String get recurringDeleteDesc => 'Isso não apaga lançamentos já gerados.';

  @override
  String get recurringPlanMonthDesc =>
      'Gere os lançamentos do mês a partir das regras.';

  @override
  String get recurringPendingConfirmation => 'Confirmação pendente';

  @override
  String recurringGeneratedSuccess(int count) {
    return 'Gerados $count lançamentos!';
  }

  @override
  String recurringGeneratedDialogBody(int count) {
    return '$count lançamentos foram criados como pendentes.';
  }

  @override
  String get commonStay => 'Ficar aqui';

  @override
  String get recurringGoToConfirm => 'Ir para confirmar';

  @override
  String get commonErrorGenerating => 'Erro ao gerar';

  @override
  String get recurringNonePlanned =>
      'Nenhuma recorrência prevista para este mês.';

  @override
  String recurringGenerateButton(int count) {
    return 'Gerar lançamentos ($count)';
  }

  @override
  String get recurringStatusToGenerate => 'A gerar';

  @override
  String get recurringStatusGenerated => 'Gerados';

  @override
  String get recurringStatusIgnored => 'Ignorados';

  @override
  String get commonNoDescription => 'Sem descrição';

  @override
  String get recurringChipGenerated => 'Gerado';

  @override
  String get recurringRestoreTooltip => 'Restaurar (Incluir na geração)';

  @override
  String get recurringIgnoreTooltip => 'Ignorar (Não gerar)';

  @override
  String recurringMissingGenerated(int count) {
    return 'Faltam $count lançamentos para gerar';
  }

  @override
  String get recurringViewPending => 'Ver pendentes';

  @override
  String get recurringViewRules => 'Ver regras';

  @override
  String get recurringNoRulesYet => 'Você ainda não tem recorrências';

  @override
  String get recurringCreateFirst => 'Criar primeira';

  @override
  String get categoriesActive => 'Categorias ativas';

  @override
  String get categoriesDeleteTitle => 'Excluir categoria?';

  @override
  String get categoriesDeleteDesc =>
      'Isso vai excluir a categoria e todas as transações vinculadas. Não dá pra desfazer.';

  @override
  String get categoriesDeleted => 'Categoria excluída';

  @override
  String get categoriesNew => 'Nova categoria';

  @override
  String get categoriesEdit => 'Editar categoria';

  @override
  String get commonPreview => 'Preview';

  @override
  String get commonName => 'Nome';

  @override
  String get categoriesParent => 'Categoria pai';

  @override
  String get categoriesNoParent => 'Sem pai';

  @override
  String get categoriesColor => 'Cor';

  @override
  String get categoriesIcon => 'Ícone';

  @override
  String get commonNameRequired => 'Nome obrigatório';

  @override
  String get dashboardMainAccounts => 'Contas principais';

  @override
  String get dashboardMainAccountsDesc => 'As que você mais usa no dia a dia';

  @override
  String get dashboardMainAccountsInfoTitle => 'Contas principais';

  @override
  String get dashboardMainAccountsInfoBody =>
      'Mostramos as contas com mais movimentos neste mês.';

  @override
  String get transactionsManageFixed => 'Gerenciar contas fixas';

  @override
  String get transactionsPendingTitle => 'Transações Pendentes';

  @override
  String get transactionsGroup => 'Agrupar por:';

  @override
  String get transactionsGroupCategory => 'Categoria';

  @override
  String get transactionsGroupRecurrence => 'Recorrência';

  @override
  String get transactionsFilterAllAccounts => 'Todas as contas';

  @override
  String get transactionsFilterAllCategories => 'Todas as categorias';

  @override
  String get transactionsFilterAllStatus => 'Todos';

  @override
  String get transactionsFilterPending => 'Pendente';

  @override
  String get transactionsFilterConfirmed => 'Confirmado';

  @override
  String get transactionsDeleteTitle => 'Excluir transação?';

  @override
  String get transactionsDeleteDesc => 'Essa ação não pode ser desfeita.';

  @override
  String get transactionsConfirmAll => 'Confirmar tudo';

  @override
  String get transactionsLabelAccount => 'Conta';

  @override
  String get transactionsLabelCategory => 'Categoria';

  @override
  String get transactionsLabelStatus => 'Status';

  @override
  String get transactionsLabelEntryAccount => 'Conta de Entrada';

  @override
  String get transactionsLabelCategoryOptional => 'Categoria (Opcional)';

  @override
  String get transactionsLabelSource => 'De (Origem)';

  @override
  String get transactionTypeTransfer => 'Transferência';

  @override
  String get transactionFormTitleNew => 'Nova Transação';

  @override
  String get transactionFormTitleEdit => 'Editar Transação';

  @override
  String get transactionFormLabelDate => 'Data';

  @override
  String get transactionFormLabelNote => 'Observação';

  @override
  String get transactionFormLabelTags => 'Tags (separadas por vírgula)';

  @override
  String get transactionFormSave => 'Salvar';

  @override
  String get transactionFormErrorSave => 'Erro ao salvar';

  @override
  String get transactionFormSuccessSave => 'Transação salva!';

  @override
  String get transactionFormConfirmDelete => 'Excluir transação?';

  @override
  String get transactionFormConfirmConversion => 'Confirmar conversão';

  @override
  String get transactionFormLabelYouSend => 'Você envia:';

  @override
  String get transactionFormLabelYouReceive => 'Você recebe:';

  @override
  String transactionFormEffectiveRate(
    String fromCurrency,
    String toCurrency,
    String rate,
  ) {
    return 'Taxa efetiva: 1 $fromCurrency ≈ $toCurrency $rate';
  }

  @override
  String get transactionFormChangeAccountTitle => 'Alterar contas?';

  @override
  String get transactionFormChangeAccountDesc =>
      'Isso pode mudar a moeda e limpar os valores informados.';

  @override
  String get transactionFormChangeAccountConfirm => 'Alterar e limpar';

  @override
  String get transactionFormTypeExpense => 'Despesa';

  @override
  String get transactionFormTypeIncome => 'Receita';

  @override
  String get transactionFormTypeTransfer => 'Transf.';

  @override
  String get transactionFormMsgRecurringError =>
      'Transação salva, mas não foi possível criar a recorrência.';

  @override
  String get transactionFormMsgRecurringSuccess =>
      'Transação salva e recorrência criada!';

  @override
  String get transactionFormRecurringConfirm => 'Confirmar conta fixa';

  @override
  String get commonConfirm => 'Confirmar';

  @override
  String get commonContinue => 'Continuar';

  @override
  String get accountsTitle => 'Contas';

  @override
  String get accountsWarningCurrency => 'Moedas precisam de revisão';

  @override
  String get accountsWarningCurrencyDesc =>
      'Algumas contas estão com moeda inválida e podem causar valores errados no dashboard.';

  @override
  String get accountsFixCurrency => 'Corrigir agora';

  @override
  String get accountsActive => 'Contas ativas';

  @override
  String get accountsCardsSection => 'Cartões';

  @override
  String get accountsCardChip => 'CARTÃO';

  @override
  String get accountsCardCurrentBill => 'Fatura atual';

  @override
  String get accountsCardViewDebts => 'Ver em Dívidas';

  @override
  String get accountsDeleteTitle => 'Excluir conta?';

  @override
  String get accountsDeleteDesc =>
      'Isso vai excluir a conta e todas as transações vinculadas. Não dá pra desfazer.';

  @override
  String get accountsDeleted => 'Conta excluída';

  @override
  String get accountsNew => 'Nova conta';

  @override
  String get accountsEdit => 'Editar conta';

  @override
  String get accountsTypeMoney => 'Dinheiro';

  @override
  String get accountsTypeBank => 'Banco';

  @override
  String get accountsTypeWallet => 'Carteira';

  @override
  String get accountsTypeBroker => 'Investimentos';

  @override
  String get accountsTypeCard => 'Cartão';

  @override
  String get accountsLabelBank => 'Banco';

  @override
  String get accountsLabelCurrency => 'Moeda';

  @override
  String get accountsLabelCurrencyCode => 'Código da moeda';

  @override
  String get accountsHintCurrencyCode => 'Ex: COP, ARS';

  @override
  String get accountsHelperCurrencyCode =>
      'Use 3-5 letras em maiúsculo. Ex: COP.';

  @override
  String get accountsErrorCurrencyInvalid =>
      'Código inválido. Use 3-5 letras (ex: COP).';

  @override
  String get budgetsTitle => 'Orçamentos';

  @override
  String get budgetsTabGoals => 'Metas';

  @override
  String get budgetsTabFixed => 'Contas fixas';

  @override
  String get budgetsMonthTitle => 'Orçamento do mês';

  @override
  String get budgetsPlanPeriod => 'Plano do período';

  @override
  String get budgetsPlanTitle => 'Plano do mês';

  @override
  String get budgetsPlanSubtitle =>
      'Registre o que planeja gastar ou receber este mês.';

  @override
  String get budgetsPlanTypeExpense => 'Gasto';

  @override
  String get budgetsPlanTypeIncome => 'Receita';

  @override
  String get budgetsPlanCategoryLabel => 'Categoria';

  @override
  String get budgetsPlanAmountLabel => 'Valor';

  @override
  String get budgetsPlanDescriptionLabel => 'Descrição (opcional)';

  @override
  String get budgetsPlanAddAction => 'Adicionar';

  @override
  String get budgetsPlanOnboardingTitle => 'Crie seu orçamento do mês';

  @override
  String get budgetsPlanOnboardingSubtitle =>
      'Adicione o que planeja gastar ou receber. Você pode ajustar depois.';

  @override
  String get budgetsPlanOnboardingNote => 'Não move dinheiro. É só um plano.';

  @override
  String get budgetsPlanSectionTitle => 'Seu plano por categorias';

  @override
  String get budgetsPlanEmptyTitle =>
      'Você ainda não tem um plano para este mês.';

  @override
  String get budgetsPlanEmptyHelper =>
      'Comece com 1 gasto ou 1 receita. Você pode melhorar depois.';

  @override
  String get budgetsPlanEmptyAction => 'Adicionar primeiro registro';

  @override
  String get budgetsPlanEmptyLink => 'Adicionar registro';

  @override
  String get budgetsPlanEntryAddedToast =>
      'Pronto. Adicionado ao seu plano do mês.';

  @override
  String get budgetsPlanPlannedExpense => 'Planejado (gastos)';

  @override
  String get budgetsPlanPlannedIncome => 'Planejado (receitas)';

  @override
  String get budgetsPlanDetailsAction => 'Ver detalhes';

  @override
  String budgetsPlanCategoryDetailTitle(Object category) {
    return 'Detalhe de $category';
  }

  @override
  String get budgetsPlanAddAnotherAction => 'Adicionar outro';

  @override
  String get budgetsPlanEmptyCategoryDetail =>
      'Você ainda não tem registros nesta categoria.';

  @override
  String get budgetsSnapshotTitle =>
      'Usamos o seu plano do mês passado como base.';

  @override
  String get budgetsSnapshotSubtitle => 'Você pode aplicar ou começar do zero.';

  @override
  String get budgetsSnapshotApplyAction => 'Usar mês anterior como base';

  @override
  String get budgetsSnapshotNotFound =>
      'Não encontramos um plano anterior para usar como base.';

  @override
  String get budgetsSnapshotStartFreshAction => 'Começar do zero';

  @override
  String get budgetsSegmentCategories => 'Categorias';

  @override
  String get budgetsSegmentDebts => 'Dívidas';

  @override
  String get budgetsSegmentSummary => 'Resumo';

  @override
  String get budgetsLabelPlanned => 'Orçamento';

  @override
  String get budgetsLabelActual => 'Gasto';

  @override
  String get budgetsLabelActualIncome => 'Recebido';

  @override
  String get budgetsLabelRemaining => 'Restante';

  @override
  String budgetsCategoryStatusRemaining(Object value) {
    return 'Você ainda tem $value';
  }

  @override
  String budgetsCategoryIncomeStatusRemaining(Object value) {
    return 'Faltam $value';
  }

  @override
  String get budgetsCategoryStatusAtLimit => 'Limite atingido';

  @override
  String get budgetsCategoryIncomeStatusAtLimit => 'Meta atingida';

  @override
  String budgetsCategoryStatusNearLimit(Object value) {
    return 'Perto do limite — Falta $value';
  }

  @override
  String budgetsCategoryIncomeStatusNearLimit(Object value) {
    return 'Perto da meta — Faltam $value';
  }

  @override
  String budgetsCategoryStatusOver(Object value) {
    return 'Você passou $value';
  }

  @override
  String budgetsCategoryIncomeStatusOver(Object value) {
    return 'Você superou $value';
  }

  @override
  String get budgetsCategoryStatusOverHelper =>
      'Você pode ajustar o orçamento ou reduzir gastos nesta categoria.';

  @override
  String get budgetsHeaderIncome => 'Receitas planejadas';

  @override
  String get budgetsHeaderExpense => 'Gastos planejados';

  @override
  String get budgetsHeaderBalance => 'Saldo planejado';

  @override
  String get budgetsEmptyTitle => 'Você ainda não configurou orçamentos.';

  @override
  String get budgetsEmptyDesc => 'Comece pelas suas categorias principais.';

  @override
  String get budgetsCreateButton => 'Configurar orçamentos';

  @override
  String get budgetsActionRemove => 'Remover do mês';

  @override
  String get budgetsSuccessRemoved =>
      'Categoria removida do orçamento deste mês';

  @override
  String get budgetsRemoveCategory => 'Remover do mês';

  @override
  String get budgetsSaveButton => 'Salvar orçamento';

  @override
  String get budgetsSaveCategoriesButton => 'Salvar plano do mês';

  @override
  String get budgetsSaveDebtsButton => 'Salvar planejamento de pagamento';

  @override
  String get budgetsSuccessSaved => 'Pronto. Seu plano do mês foi salvo.';

  @override
  String get budgetsMonthSummaryTitle => 'Resumo do mês';

  @override
  String get budgetsMonthSummaryPlannedCategories =>
      'Gastos planejados (categorias)';

  @override
  String get budgetsMonthSummaryPlannedDebts =>
      'Pagamentos de dívidas planejados';

  @override
  String get budgetsMonthSummaryTotalOutflow => 'Total de saídas planejadas';

  @override
  String get budgetsMonthSummaryOtherCurrencies =>
      'Outras moedas (sem conversão)';

  @override
  String get budgetsDebtPlannedTitle => 'Dívidas (pagamentos planejados)';

  @override
  String get budgetsDebtPlannedSubtitle =>
      'Reserve quanto você vai pagar este mês. Não é um gasto novo.';

  @override
  String get budgetsDebtPaymentNote =>
      'Pagar dívida não é gasto novo. É pagar o que você já deve.';

  @override
  String get budgetsDebtPayLabel => 'Vou pagar';

  @override
  String get budgetsDebtOweLabel => 'Devo';

  @override
  String get budgetsDebtQuickMin => 'Mínimo';

  @override
  String get budgetsDebtQuickTotal => 'Total';

  @override
  String get budgetsDebtOverpayWarning =>
      'Você está pagando mais do que deve. Tem certeza?';

  @override
  String budgetsDebtPaidPlanned(Object paid, Object planned) {
    return 'Pago: $paid / $planned planejado';
  }

  @override
  String get budgetsDebtActionZeroAll => 'Zerar tudo';

  @override
  String get budgetsDebtActionSuggest => 'Sugerir pagamentos';

  @override
  String budgetsDebtOverpaid(Object amount) {
    return 'Você pagou $amount a mais que o planejado.';
  }

  @override
  String budgetsDebtRemaining(Object amount) {
    return 'Faltam $amount para seu plano.';
  }

  @override
  String get budgetsDebtEmptyState => 'Você não tem dívidas registradas.';

  @override
  String get budgetsDebtMinimumWarning => 'Seu plano está abaixo do mínimo.';

  @override
  String budgetsDebtTotalPlannedLabel(Object currency) {
    return 'Total planejado ($currency)';
  }

  @override
  String get budgetsSummaryCategoriesTitle => 'Gastos por categoria';

  @override
  String get budgetsSummaryDebtsTitle => 'Pagamentos planejados de dívidas';

  @override
  String get budgetsSummaryPlanTitle => 'Resumo do mês';

  @override
  String get budgetsSummaryPlannedExpense => 'Total planejado (gastos)';

  @override
  String get budgetsSummaryPlannedIncome => 'Total planejado (receitas)';

  @override
  String get budgetsSummaryEstimatedAvailable => 'Disponível estimado';

  @override
  String get budgetsSummaryPlannedDebts => 'Total de pagamentos planejados';

  @override
  String get budgetsSummaryTotalPlanned => 'Total planejado';

  @override
  String get budgetsSummaryTotalSpent => 'Total gasto';

  @override
  String budgetsSummaryOverspentCount(Object count) {
    return 'Categorias estouradas: $count';
  }

  @override
  String get budgetsSummaryViewCategories => 'Ver categorias';

  @override
  String get budgetsSummaryViewDebts => 'Ver dívidas';

  @override
  String budgetsSummaryNextDueDay(Object day) {
    return 'Próximo vencimento: dia $day';
  }

  @override
  String get budgetsCategoriesTitle => 'Gastos por categoria';

  @override
  String get accountsSuccessCurrencyFixed => 'Moedas corrigidas com sucesso!';

  @override
  String get goalsTitle => 'Metas';

  @override
  String get goalsMyGoals => 'Suas metas';

  @override
  String get goalsNew => 'Nova meta';

  @override
  String get goalsEdit => 'Editar meta';

  @override
  String get goalsCreate => 'Criar meta';

  @override
  String get goalsNameLabel => 'Nome da meta';

  @override
  String get goalsNameHint => 'Ex: Fundo de emergência';

  @override
  String get goalsTargetAmount => 'Valor alvo';

  @override
  String get goalsDetailsOptional => 'Detalhes (opcional)';

  @override
  String get goalsTargetDate => 'Data alvo (opcional)';

  @override
  String get goalsNoDate => 'Sem data';

  @override
  String goalsSuggestedMonthly(Object amount) {
    return 'Sugerido: $amount por mês';
  }

  @override
  String get goalsMonthlyContribution => 'Aporte mensal (opcional)';

  @override
  String get goalsLinkedAccount => 'Conta vinculada (opcional)';

  @override
  String get goalsContributionTitle => 'Registrar aporte';

  @override
  String get goalsContributionValue => 'Valor';

  @override
  String get goalsNoAccounts => 'Você não tem contas ativas.';

  @override
  String get goalsDate => 'Data';

  @override
  String get goalsNoteOptional => 'Nota (opcional)';

  @override
  String get goalsErrorName => 'Falta o nome';

  @override
  String get goalsErrorAmount => 'O valor deve ser maior que 0';

  @override
  String get goalsQuickAddConfigError =>
      'Configure um aporte mensal para usar aporte rápido';

  @override
  String get goalsAccountConfigError =>
      'Configure uma conta para usar aporte rápido';

  @override
  String goalsContributionSuccess(Object amount) {
    return 'Aporte de $amount registrado';
  }

  @override
  String goalsProjectionIdeal(Object amount, Object date) {
    return 'Se guardar $amount/mês, chega em $date.';
  }

  @override
  String goalsProjectionOnTrack(Object amount, Object date) {
    return 'Guardando $amount/mês, chega em $date.';
  }

  @override
  String goalsProjectionOnTrackNoDate(Object amount) {
    return 'Guardando $amount/mês';
  }

  @override
  String goalsProjectionOffTrack(Object amount, Object date) {
    return 'Para chegar em $date, precisa guardar $amount/mês.';
  }

  @override
  String goalsProjectionDateOnly(Object date) {
    return 'Meta $date';
  }

  @override
  String goalsRemaining(Object amount) {
    return 'Restante $amount';
  }

  @override
  String get goalsQuickAdd => 'Aporte rápido';

  @override
  String get goalsCustomize => 'Personalizar';

  @override
  String get goalsViewDetails => 'Ver detalhes';

  @override
  String get goalsEmptyTitle => 'Suas metas começam aqui';

  @override
  String get goalsEmptyDescription =>
      'Meta é um “alvo” pra separar dinheiro aos poucos. Você escolhe o valor e o prazo. Dá pra mudar depois.';

  @override
  String get goalsEmptyBullet1 => '• Veja quanto falta pra chegar lá';

  @override
  String get goalsEmptyBullet2 => '• Acompanhe sem contas complicadas';

  @override
  String get goalsEmptyBullet3 => '• Mantenha foco no que importa';

  @override
  String get goalsEmptyExamplesTitle => 'Ideias prontas (toque para usar)';

  @override
  String get goalsEmptyExampleEmergency => 'Fundo de emergência';

  @override
  String get goalsEmptyExampleTrip => 'Viagem';

  @override
  String get goalsEmptyExampleBigPurchase => 'Comprar algo grande';

  @override
  String get goalsEmptyExampleBillsBuffer => 'Reserva para contas fixas';

  @override
  String get goalsEmptyCta => 'Criar minha primeira meta';

  @override
  String get goalsEmptyMicrocopy => 'Você pode editar ou apagar depois.';

  @override
  String get goalsHelpToggle => 'O que é isso?';

  @override
  String get debtsTitle => 'Dívidas';

  @override
  String get debtsActiveLiabilities => 'Passivos ativos';

  @override
  String get debtsNew => 'Nova dívida';

  @override
  String get debtsEdit => 'Editar dívida';

  @override
  String get debtsName => 'Nome';

  @override
  String get debtsType => 'Tipo';

  @override
  String get debtsTypeCreditCard => 'Cartão de Crédito';

  @override
  String get debtsTypeLoan => 'Empréstimo';

  @override
  String get debtsTypeOther => 'Outro';

  @override
  String get debtsNoCreditCardAccount =>
      'Você não tem contas do tipo \'Cartão de Crédito\'.';

  @override
  String get debtsCreateCardAccount => 'Criar conta Cartão agora';

  @override
  String get debtsLinkedAccount => 'Conta do cartão (Onde caem as compras)';

  @override
  String get debtsInitialBalance => 'Saldo inicial';

  @override
  String get debtsInitialBalanceCurrent => 'Saldo atual (opcional)';

  @override
  String get debtsInitialBalanceHelper =>
      'Se você já tem saldo a pagar neste cartão hoje, informe aqui. Se não, deixe 0.';

  @override
  String get debtsInitialBalanceWarning =>
      'Saldo inicial não pode ser alterado. Ajuste registrando uma compra/pagamento.';

  @override
  String get debtsNoPayingAccount =>
      'Sem contas bancárias/dinheiro para pagar a fatura.';

  @override
  String get debtsPayingAccount => 'Conta pagadora padrão (Opcional)';

  @override
  String get debtsPayingAccountHelper =>
      'Conta sugerida quando você registrar o pagamento da fatura.';

  @override
  String get debtsDueDate => 'Dia de vencimento';

  @override
  String get debtsDueDateHint => 'Ex: 10';

  @override
  String get debtsDueDateError => 'Entre 1 e 31';

  @override
  String get debtsAdvanced => 'Avançado (opcional)';

  @override
  String get debtsMinimumPayment => 'Mínimo a pagar';

  @override
  String get debtsInterestRate => 'Taxa anual (%)';

  @override
  String get debtsErrorSelectAccount => 'Selecione a conta do cartão';

  @override
  String get debtsErrorNoLinkedAccount =>
      'Esta dívida não tem conta vinculada. Edite a dívida para vincular uma conta do tipo Cartão.';

  @override
  String get debtsQuickAccountTitle => 'Criar conta rápida';

  @override
  String get debtsQuickAccountName => 'Nome da conta';

  @override
  String debtsDueDayLabel(Object day) {
    return 'Vence dia $day';
  }

  @override
  String get debtsCurrentBill => 'Fatura atual:';

  @override
  String get debtsAvailableCredit => 'Crédito disponível:';

  @override
  String get debtsAllPaid => 'Tudo pago 🎉';

  @override
  String get debtsActionCharge => 'Registrar Compra';

  @override
  String get debtsActionPay => 'Pagar fatura';

  @override
  String get debtsDialogPaidTitle => 'Tudo pago ✅';

  @override
  String get debtsDialogPaidBody => 'Você não tem saldo a pagar neste cartão.';

  @override
  String get debtsDialogPaidAction => 'Pagar mesmo assim';

  @override
  String get debtsDialogLinkTitle => 'Conta não vinculada';

  @override
  String get debtsDialogLinkBody =>
      'Para pagar a fatura, você precisa vincular uma conta do tipo \'Cartão de Crédito\' a esta dívida.';

  @override
  String get debtsDialogLinkAction => 'Vincular agora';

  @override
  String get monthSummaryTitle => 'Resumo geral do mês';

  @override
  String get monthSummaryTabCategories => 'Por categoria';

  @override
  String get monthSummaryTabAccounts => 'Por conta';

  @override
  String get monthSummaryTabOtherCurrencies => 'Outras moedas';

  @override
  String get monthSummaryHeaderHelper =>
      'Sem conversão automática. Valores por moeda.';

  @override
  String monthSummaryEmptyPrimary(Object currency) {
    return 'Sem movimentos em $currency neste mês.';
  }

  @override
  String get monthSummarySeeOtherCurrencies => 'Veja em Outras moedas';

  @override
  String monthSummaryTotalSpent(Object currency) {
    return 'Total gastos ($currency):';
  }

  @override
  String get monthSummaryOtherCurrencies => 'Outras moedas (sem conversão):';

  @override
  String get monthSummaryNoAccounts => 'Nenhuma conta encontrada';

  @override
  String get monthSummaryIncome => 'Entradas';

  @override
  String get monthSummaryPayments => 'Pagamentos';

  @override
  String get monthSummaryExpenses => 'Saídas';

  @override
  String get monthSummaryPurchases => 'Compras';

  @override
  String get monthSummaryNetMonth => 'Variação no mês';

  @override
  String get monthSummaryBalanceMonth => 'Saldo do mês';

  @override
  String get monthSummaryViewInvoice => 'Ver fatura/histórico';

  @override
  String get monthSummaryViewTransactions => 'Ver transações';

  @override
  String get monthSummaryNoOtherCurrencies => 'Nenhuma outra moeda movimentada';

  @override
  String get monthSummaryOtherCurrenciesSubtitle =>
      'Os valores abaixo não são convertidos para a moeda principal.';

  @override
  String get monthSummaryNet => 'Líquido';

  @override
  String get authLoginTitle => 'Entrar';

  @override
  String get authContinueGoogle => 'Continuar com Google';

  @override
  String get authContinueApple => 'Continuar com Apple';

  @override
  String get authOr => 'ou';

  @override
  String get authLoginEmail => 'Entrar com e-mail';

  @override
  String get authEmailLabel => 'Email';

  @override
  String get authPasswordLabel => 'Senha';

  @override
  String get authButtonLogin => 'Entrar';

  @override
  String get authButtonRegister => 'Criar conta';

  @override
  String get authLoadingLogin => 'Entrando...';

  @override
  String get authLoadingRegister => 'Criando conta...';

  @override
  String get authSwitchToLogin => 'Já tenho conta';

  @override
  String get authSwitchToRegister => 'Criar nova conta';

  @override
  String get authDisclaimer =>
      'Usamos seu login apenas para acessar sua conta.';

  @override
  String get authRegisterTitle => 'Criar conta';

  @override
  String get authRegisterQuick => 'Registro rápido';

  @override
  String get authRegisterSubtitle => 'Só email e senha. Em menos de 30s.';

  @override
  String get transactionFormErrorCreate => 'Erro ao salvar a transação.';

  @override
  String get transactionFormSuccessUpdate =>
      'Transação atualizada com sucesso!';

  @override
  String transactionFormErrorUpdate(String error) {
    return 'Erro ao salvar: $error';
  }

  @override
  String get transactionFormLabelCardPurchase => 'Compra no cartão';

  @override
  String get transactionFormLabelSource => 'Conta de Saída';

  @override
  String get transactionsLabelDestination => 'Para (Destino)';

  @override
  String get transactionsActionImportCsv => 'Importar CSV';

  @override
  String get transactionFormRecurringError =>
      'Transação salva, mas não foi possível criar a recorrência.';

  @override
  String get transactionFormRecurringSuccess =>
      'Transação salva e recorrência criada!';

  @override
  String recurringSummaryDay(Object day) {
    return 'Todo dia $day';
  }

  @override
  String get navDashboard => 'Início';

  @override
  String get navTransactions => 'Transações';

  @override
  String get navBudgets => 'Orçamentos';

  @override
  String get navSettings => 'Ajustes';

  @override
  String get dashboardShortcutTitle => 'Resumo do mês por categorias';

  @override
  String get dashboardShortcutDesc =>
      'Sem conversão automática.\nToque para ver gastos por moeda e categoria.';

  @override
  String get dashboardQuickActionsTitle => 'Ações rápidas';

  @override
  String get dashboardQuickActionExpense => 'Gasto';

  @override
  String get dashboardQuickActionIncome => 'Receita';

  @override
  String get dashboardQuickActionTransfer => 'Transferir';

  @override
  String get dashboardQuickActionFixed => 'Contas fixas';

  @override
  String get cardLabelCredit => 'CARTÃO';

  @override
  String get cardLabelBalancePay => 'Saldo a pagar';

  @override
  String cardLabelDueDay(Object day) {
    return 'Vence dia $day';
  }

  @override
  String get cardLabelPayments => 'Pagamentos';

  @override
  String get cardLabelPurchases => 'Compras';

  @override
  String get cardLabelIncomes => 'Entradas';

  @override
  String get cardLabelExpenses => 'Saídas';

  @override
  String get cardLabelMonthBalance => 'Saldo do mês';

  @override
  String get cardLabelNoMovements => 'Sem movimentos este mês';

  @override
  String get cardActionView => 'Ver transações';

  @override
  String get debtsSectionTitle => 'Dívidas';

  @override
  String get debtsEmptyState => 'Você ainda não cadastrou dívidas.';

  @override
  String get debtsActionAdd => 'Adicionar dívida';

  @override
  String get debtsActionViewAll => 'Ver dívidas';

  @override
  String get debtsPaidMonth => 'Pago este mês: ';

  @override
  String get debtsTotalToPay => 'Total a pagar';

  @override
  String debtsNextDue(Object date, Object name) {
    return 'Próximo: $date — $name';
  }

  @override
  String get debtsPaymentDisclaimer =>
      'Registra um pagamento (não é cobrança automática).';

  @override
  String get commonUnderstood => 'Entendi';

  @override
  String get dashboardOtherAccountsTitle => 'Outras contas';

  @override
  String get dashboardOtherAccountsDesc =>
      'Contas menos usadas ou sem movimentos no mês';

  @override
  String get dashboardOtherAccountsNoMovements => 'Sem movimentos neste mês';

  @override
  String dashboardOtherAccountsMonthBalance(Object amount) {
    return 'Saldo do mês: $amount';
  }

  @override
  String dashboardOtherAccountsViewAll(Object count) {
    return 'Ver todas ($count)';
  }

  @override
  String get transactionFormLabelInvoicePayment => 'Pagamento de fatura';

  @override
  String get transactionFormLabelCardSourceError =>
      'Cartão não pode ser conta de origem. Use sua conta bancária.';

  @override
  String get transactionFormLabelDebtWarning =>
      'Isso aumenta sua dívida. Não sai do banco agora.';

  @override
  String get transactionFormLabelPaymentValue => 'Valor do pagamento';

  @override
  String get transactionFormHelperPayment => 'Sai do banco e abate na fatura.';

  @override
  String get transactionFormLabelTransferValue => 'Valor';

  @override
  String get transactionFormHelperTransfer =>
      'Valor que sai da origem e entra no destino.';

  @override
  String transactionFormLabelSentValue(String currency) {
    return 'Você envia ($currency)';
  }

  @override
  String get transactionFormHelperSent => 'Valor que sai da conta de origem.';

  @override
  String transactionFormLabelReceivedValue(String currency) {
    return 'Você recebe ($currency)';
  }

  @override
  String get transactionFormHelperReceived =>
      'Valor que entra na conta de destino.';

  @override
  String get transactionFormLabelSelectSourceDest =>
      'Selecione Origem e Destino';

  @override
  String get transactionFormHelperSelectSourceDest =>
      'Escolha as contas para liberar o valor.';

  @override
  String get transactionFormLabelAlreadyCleared => 'Já entrou no saldo?';

  @override
  String get transactionFormStatusCleared => 'Confirmada';

  @override
  String get transactionFormStatusPending => 'Pendente';

  @override
  String get transactionFormHelperStatus =>
      'Se estiver pendente, pode mudar depois.';

  @override
  String get transactionFormLabelMoreOptions => 'Mais opções';

  @override
  String get transactionFormLabelMoreOptionsSubtitle =>
      'Nota, Tags, Recorrência';

  @override
  String get transactionFormLabelMoreOptionsRecurring => 'Recorrente';

  @override
  String get transactionFormLabelRepeat => 'Repetir automaticamente';

  @override
  String get transactionFormHelperRepeat =>
      'Cria uma conta fixa para você não esquecer.';

  @override
  String get transactionFormLabelFrequencyMonthly => 'Mensal';

  @override
  String get transactionFormLabelFrequencyWeekly => 'Semanal';

  @override
  String get transactionFormActionManageFixed => 'Gerenciar contas fixas';

  @override
  String get transactionFormLabelSaveTemplate => 'Salvar como Template';

  @override
  String get transactionFormLabelTemplateName => 'Nome do Template';

  @override
  String get transactionFormActionSaving => 'Salvando...';

  @override
  String get transactionFormValidationSameAccount =>
      'Selecione contas diferentes.';

  @override
  String get transactionFormCategoryPurchase => 'Categoria da compra';

  @override
  String get transactionFormInvoiceSource => 'Cartão (Fatura)';

  @override
  String get transactionFormPaymentSuccess => 'Pagamento de fatura registrado!';

  @override
  String transactionFormPaymentError(String error) {
    return 'Erro ao registrar pagamento: $error';
  }

  @override
  String get transactionFormChargeSuccess => 'Compra registrada!';

  @override
  String transactionFormChargeError(String error) {
    return 'Erro ao salvar compra: $error';
  }

  @override
  String get commonToday => 'Hoje';

  @override
  String get commonYesterday => 'Ontem';

  @override
  String get commonFrom => 'de';

  @override
  String get commonTo => 'para';

  @override
  String get commonNoAccount => 'Sem conta';

  @override
  String get transactionsEmptyState => 'Nenhuma transação encontrada';

  @override
  String get onboardingPreferencesTitle => 'Preferências';

  @override
  String get onboardingPreferencesDesc =>
      'Escolha como você quer ver o app. Dá pra mudar depois.';

  @override
  String get onboardingFieldLanguage => 'Idioma';

  @override
  String get onboardingFieldCountry => 'País';

  @override
  String get onboardingFieldCurrency => 'Moeda principal';

  @override
  String get onboardingCreateAccountTitle => 'Crie sua primeira conta';

  @override
  String get onboardingCreateAccountDesc =>
      'Ex.: banco, dinheiro, carteira. Você pode adicionar mais depois.';

  @override
  String get onboardingFieldInitialBalance => 'Saldo inicial (opcional)';

  @override
  String get onboardingHelperInitialBalance =>
      'Se não souber agora, deixe em branco.';

  @override
  String get onboardingErrorNoAccount =>
      'Crie pelo menos 1 conta para continuar.';

  @override
  String get onboardingCategoriesTitle => 'Escolha suas categorias';

  @override
  String get onboardingCategoriesDesc =>
      'Deixe marcado o que você usa. Dá pra mudar depois.';

  @override
  String get onboardingActionSelectAll => 'Marcar tudo';

  @override
  String get onboardingActionDeselectAll => 'Desmarcar tudo';

  @override
  String get catHousing => 'Moradia (aluguel/condomínio)';

  @override
  String get catUtilities => 'Contas da casa (água, luz, gás)';

  @override
  String get catInternet => 'Internet e celular';

  @override
  String get catGroceries => 'Mercado';

  @override
  String get catRestaurants => 'Restaurantes';

  @override
  String get catTransport => 'Transporte (ônibus/uber)';

  @override
  String get catFuel => 'Combustível';

  @override
  String get catCarMaintenance => 'Manutenção do carro';

  @override
  String get catHealth => 'Saúde';

  @override
  String get catPharmacy => 'Farmácia';

  @override
  String get catEducation => 'Educação (escola/cursos)';

  @override
  String get catCreditCard => 'Cartão de crédito (gastos)';

  @override
  String get catDebts => 'Dívidas e empréstimos';

  @override
  String get catFees => 'Taxas e tarifas';

  @override
  String get catSubscriptions => 'Assinaturas (streaming/apps)';

  @override
  String get catPersonal => 'Cuidados pessoais';

  @override
  String get catClothing => 'Roupas';

  @override
  String get catWork => 'Trabalho (ferramentas/serviços)';

  @override
  String get catTaxes => 'Impostos';

  @override
  String get voiceTitleExpense => 'Registrar despesa';

  @override
  String get voiceTitleIncome => 'Registrar receita';

  @override
  String get voiceTitleTransfer => 'Registrar transferência';

  @override
  String get voiceButtonType => 'Digitar';

  @override
  String get voiceStatusListening => 'Ouvindo...';

  @override
  String get voiceStatusManual => 'Modo manual';

  @override
  String get voiceStatusWaiting => 'Aguardando...';

  @override
  String get voiceTranscriptPlaceholder => 'A transcrição aparecerá aqui';

  @override
  String get voicePermissionButton => 'Permitir microfone';

  @override
  String get voiceChipAmount => 'Valor';

  @override
  String get voiceChipAccount => 'Conta';

  @override
  String get voiceChipDate => 'Data';

  @override
  String get voiceChipCategory => 'Categoria';

  @override
  String get voicePromptAmount => 'Diga o valor';

  @override
  String get voicePromptAccount => 'De qual conta sai esse gasto?';

  @override
  String get voicePromptDate => 'Foi hoje?';

  @override
  String get voicePromptCategory => 'Qual categoria?';

  @override
  String get voiceAmountLabel => 'Digite o valor';

  @override
  String get voiceAccountLabel => 'Escolha a conta';

  @override
  String get voiceAccountAll => 'Ver todas';

  @override
  String get voiceDateLabel => 'Quando foi?';

  @override
  String get voiceDateToday => 'Hoje';

  @override
  String get voiceDateYesterday => 'Ontem';

  @override
  String get voiceDateOther => 'Outro dia';

  @override
  String get voiceCategoryLabel => 'Escolha a categoria';

  @override
  String get voiceCategoryAll => 'Ver todas';

  @override
  String get voiceCategoryUncategorized => 'Sem categoria (Outros)';

  @override
  String get voiceConfirmTitle => 'Confirmação';

  @override
  String get voiceEditButton => 'Editar';

  @override
  String get voiceSavingLabel => 'Salvando...';

  @override
  String get voiceSuccessLabel => 'Registrado';

  @override
  String get voicePrimaryContinue => 'Continuar';

  @override
  String get voicePrimaryConfirm => 'Confirmar';

  @override
  String get voicePrimarySaving => 'Salvando';

  @override
  String get voicePrimaryNew => 'Registrar outro';

  @override
  String get voiceSecondaryCancel => 'Cancelar';

  @override
  String get voiceSecondaryClose => 'Fechar';

  @override
  String get voiceSnackbarMissingAccount => 'Falta escolher conta de saída';

  @override
  String get voiceSnackbarMissingDate => 'Falta escolher a data';

  @override
  String get voiceSnackbarMissingCategory => 'Falta escolher categoria';

  @override
  String get voiceSnackbarInvalidAmount => 'O valor deve ser maior que 0';

  @override
  String get voiceSnackbarSaveError => 'Erro ao salvar';

  @override
  String get voiceSnackbarAmountRequired => 'Digite um valor válido';

  @override
  String get voiceSearchAccount => 'Buscar conta';

  @override
  String get voiceSearchCategory => 'Buscar categoria';

  @override
  String get voiceErrorNotUnderstoodType => 'Não entendi. Pode digitar?';

  @override
  String get voiceErrorRepeat => 'Não entendi. Pode repetir?';

  @override
  String get voiceErrorMicPermission => 'Permissão de microfone negada';

  @override
  String get voiceMultipleAccounts =>
      'Encontrei mais de uma conta. Toque para escolher.';

  @override
  String get voiceMultipleCategories =>
      'Encontrei mais de uma categoria. Toque para escolher.';

  @override
  String get voiceNoAccounts => 'Você ainda não tem contas cadastradas.';

  @override
  String get voiceNoCategories => 'Você ainda não tem categorias cadastradas.';

  @override
  String voiceAccountsListTemplate(Object names) {
    return 'Suas contas são: $names.';
  }

  @override
  String voiceCategoriesListTemplate(Object names) {
    return 'As categorias são: $names.';
  }

  @override
  String voiceConfirmPromptTemplate(Object summary) {
    return '$summary Diga confirmado ou cancelar.';
  }

  @override
  String get voiceEditPrompt => 'Ok. Edite os campos abaixo.';

  @override
  String get voiceDateSelectPrompt => 'Ok. Escolha a data abaixo.';

  @override
  String get voiceConjunction => 'e';

  @override
  String voiceSummaryTemplate(
    Object account,
    Object amount,
    Object category,
    Object date,
  ) {
    return 'Vou registrar: $amount em $category, da conta $account, $date.';
  }

  @override
  String get settingsVoiceAssistantTitle => 'Voz do assistente';

  @override
  String get settingsVoiceAssistantDesc =>
      'Ative para ouvir perguntas por voz durante o registro.';

  @override
  String budgetsHeaderCompactExpenses(Object value) {
    return 'Gastos planejados: $value';
  }

  @override
  String budgetsHeaderCompactIncomes(Object value) {
    return 'Receitas planejadas: $value';
  }

  @override
  String budgetsHeaderCompactBalance(Object value) {
    return 'Balanço planejado: $value';
  }

  @override
  String get budgetsActionAddRecord => '+ Adicionar';

  @override
  String get budgetsModalTitle => 'Adicionar ao plano';

  @override
  String get budgetsModalButtonAdd => 'Adicionar';

  @override
  String get budgetsModalConfirmAdded => 'Adicionado ao plano';

  @override
  String get budgetsEntryDialogDeleteConfirm => 'Remover este item do plano?';

  @override
  String get budgetsEntryDialogDeleteAction => 'Sim, remover';

  @override
  String get budgetsStatusExceededChip => 'Excedido';

  @override
  String budgetsStatusOverText(Object value) {
    return 'Você passou $value';
  }

  @override
  String get budgetsStatusLimitReached => 'Limite atingido';

  @override
  String budgetsStatusRemainingText(Object value) {
    return 'Você ainda tem $value';
  }
}
