// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Portuguese (`pt`).
class AppLocalizationsPt extends AppLocalizations {
  AppLocalizationsPt([String locale = 'pt']) : super(locale);

  @override
  String get appTitle => 'Desquadra';

  @override
  String get drawerFastAccess => 'ACESSO RÁPIDO';

  @override
  String get drawerDashboard => 'Dashboard';

  @override
  String get drawerTransactions => 'Transações';

  @override
  String get drawerBudgets => 'Orçamentos';

  @override
  String get drawerMonthSummary => 'Resumo do mês por categorias';

  @override
  String get drawerManagement => 'GESTÃO';

  @override
  String get drawerCategories => 'Categorias';

  @override
  String get drawerAccounts => 'Contas';

  @override
  String get drawerSettings => 'AJUSTES';

  @override
  String get drawerAccount => 'CONTA';

  @override
  String get drawerLogout => 'Sair';

  @override
  String get settingsTitle => 'Ajustes';

  @override
  String get settingsManageShortcutTitle => 'Gerenciar';

  @override
  String get settingsManageShortcutDesc => 'Categorias, Contas, Metas';

  @override
  String get settingsManageShortcutButton => 'Abrir menu';

  @override
  String get drawerDebts => 'Dívidas';

  @override
  String get drawerGoals => 'Metas';

  @override
  String get drawerRecurring => 'Contas fixas';

  @override
  String get settingsPreferences => 'Preferências';

  @override
  String get settingsMainCurrency => 'Moeda principal';

  @override
  String get settingsMainCurrencyDesc =>
      'O Resumo do mês usa apenas esta moeda. Outras moedas aparecem nas contas (sem conversão).';

  @override
  String get settingsAutomation => 'Automação';

  @override
  String get settingsAutoGenerate => 'Gerar automaticamente';

  @override
  String get settingsAutoGenerateDesc =>
      'Cria lançamentos de contas fixas ao iniciar o mês (não movimenta dinheiro).';

  @override
  String get settingsAutoGenerateInfo =>
      'As transações serão criadas como pendentes na data prevista.';

  @override
  String get settingsVersion => 'Versão';

  @override
  String get commonCancel => 'Cancelar';

  @override
  String get commonSave => 'Salvar';

  @override
  String get currencyOther => 'Outra';

  @override
  String get currencyCustomLabel => 'Código (ex: COP)';

  @override
  String get currencyCustomHint => '3-5 letras maiúsculas';

  @override
  String get currencyInvalid => 'Código inválido. Use 3 a 5 letras (A-Z).';

  @override
  String get settingsAccountSection => 'Conta';

  @override
  String get successSettingsUpdate => 'Configuração salva com sucesso!';

  @override
  String errorSettingsUpdate(String error) {
    return 'Erro ao atualizar configuração: $error';
  }

  @override
  String settingsVersionValue(String version) {
    return 'Versão $version';
  }

  @override
  String get appTagline => 'Finanças simples, sem complicação.';

  @override
  String drawerMainCurrency(String currency) {
    return 'Moeda principal: $currency';
  }

  @override
  String get settingsLanguage => 'Idioma';

  @override
  String get languageEnglish => 'Inglês';

  @override
  String get languagePortuguese => 'Português';

  @override
  String get languageSpanish => 'Espanhol';

  @override
  String get onboardingFeature1 => '• Registrar gasto em 3 toques';

  @override
  String get onboardingFeature2 => '• Ver saldo real e planejado';

  @override
  String get onboardingFeature3 => '• Tudo em um só lugar, sem jargão';

  @override
  String get onboardingStartFast => 'Começar rápido';

  @override
  String get commonSkip => 'Pular';

  @override
  String get onboardingWelcome => 'Bem-vindo!';

  @override
  String get onboardingDescription =>
      'Vamos deixar tudo pronto em menos de 60 segundos.';

  @override
  String get onboardingUseExamples => 'Quero usar exemplos';

  @override
  String get onboardingSkipDescription => 'Você pode pular e ajustar depois.';

  @override
  String get onboardingCreateAccount =>
      'Criaremos uma conta para você registrar gastos.';

  @override
  String get onboardingChooseCreation => 'Escolha o que quer criar agora.';

  @override
  String get onboardingCreateBudget => 'Criar orçamento base';

  @override
  String get onboardingCreateBudgetDesc => 'Você poderá editar depois.';

  @override
  String get onboardingFirstTransaction =>
      'Você já pode registrar seu primeiro gasto.';

  @override
  String get onboardingAddCards =>
      'Adicione seus cartões para controlar faturas.';

  @override
  String get commonDelete => 'Excluir';

  @override
  String get transactionTypeExpense => 'Despesa';

  @override
  String get transactionTypeIncome => 'Receita';

  @override
  String get commonActive => 'Ativa';

  @override
  String get recurringTitle => 'Recorrências';

  @override
  String get recurringMyRules => 'Minhas regras';

  @override
  String get recurringOpenPlanner => 'Abrir planejador';

  @override
  String recurringPendingItems(int count) {
    return 'Você tem $count itens para confirmar.';
  }

  @override
  String get commonView => 'Ver';

  @override
  String get commonEdit => 'Editar';

  @override
  String get recurringPlanMonth => 'Planejar Mês';

  @override
  String get recurringGeneratedEntries => 'Lançamentos gerados';

  @override
  String get commonBack => 'Voltar';

  @override
  String get commonNext => 'Próximo';

  @override
  String get commonFinish => 'Finalizar';

  @override
  String get onboardingMainAccount => 'Conta principal';

  @override
  String get accountNameLabel => 'Nome da conta';

  @override
  String get accountTypeLabel => 'Tipo';

  @override
  String get accountTypeBank => 'Banco';

  @override
  String get accountTypeCash => 'Dinheiro';

  @override
  String get accountTypeWallet => 'Carteira';

  @override
  String get onboardingBaseCategories => 'Categorias base';

  @override
  String get onboardingAllSet => 'Tudo pronto';

  @override
  String get onboardingExamplesCreated =>
      'Criamos exemplos básicos para você ajustar depois.';

  @override
  String get onboardingMinimumCreated => 'Criamos o mínimo para você começar.';

  @override
  String get onboardingCreditCards => 'Cartões de crédito';

  @override
  String get onboardingCardName => 'Nome do cartão';

  @override
  String get onboardingNoCards =>
      'Nenhum cartão adicionado. Clique em + para adicionar ou Próximo para pular.';

  @override
  String get recurringAppDescription => 'O app só registra. Não cobra.';

  @override
  String get commonNew => 'Nova';

  @override
  String get recurringInactive => 'Inativas';

  @override
  String get recurringNewRule => 'Nova recorrência';

  @override
  String get recurringEmptyState =>
      'Crie uma recorrência para planejar seu mês em segundos.';

  @override
  String recurringFrequencyMonthly(int day) {
    return 'Todo mês dia $day';
  }

  @override
  String get recurringFrequencyWeekly => 'Semanal';

  @override
  String get recurringFrequencyYearly => 'Anual';

  @override
  String get commonComingSoon => 'Em breve';

  @override
  String get commonPause => 'Pausar';

  @override
  String get commonActivate => 'Ativar';

  @override
  String get recurringDeleteTitle => 'Excluir regra?';

  @override
  String get recurringDeleteDesc => 'Isso não apaga lançamentos já gerados.';

  @override
  String get recurringPlanMonthDesc =>
      'Gere os lançamentos do mês a partir das regras.';

  @override
  String get recurringPendingConfirmation => 'Confirmação pendente';

  @override
  String recurringGeneratedSuccess(int count) {
    return 'Gerados $count lançamentos!';
  }

  @override
  String recurringGeneratedDialogBody(int count) {
    return '$count lançamentos foram criados como pendentes.';
  }

  @override
  String get commonStay => 'Ficar aqui';

  @override
  String get recurringGoToConfirm => 'Ir para confirmar';

  @override
  String get commonErrorGenerating => 'Erro ao gerar';

  @override
  String get recurringNonePlanned =>
      'Nenhuma recorrência prevista para este mês.';

  @override
  String recurringGenerateButton(int count) {
    return 'Gerar lançamentos ($count)';
  }

  @override
  String get recurringStatusToGenerate => 'A gerar';

  @override
  String get recurringStatusGenerated => 'Gerados';

  @override
  String get recurringStatusIgnored => 'Ignorados';

  @override
  String get commonNoDescription => 'Sem descrição';

  @override
  String get recurringChipGenerated => 'Gerado';

  @override
  String get recurringRestoreTooltip => 'Restaurar (Incluir na geração)';

  @override
  String get recurringIgnoreTooltip => 'Ignorar (Não gerar)';

  @override
  String recurringMissingGenerated(int count) {
    return 'Faltam $count lançamentos para gerar';
  }

  @override
  String get recurringViewPending => 'Ver pendentes';

  @override
  String get recurringViewRules => 'Ver regras';

  @override
  String get recurringNoRulesYet => 'Você ainda não tem recorrências';

  @override
  String get recurringCreateFirst => 'Criar primeira';

  @override
  String get categoriesActive => 'Categorias ativas';

  @override
  String get categoriesDeleteTitle => 'Excluir categoria?';

  @override
  String get categoriesDeleteDesc =>
      'Isso vai excluir a categoria e todas as transações vinculadas. Não dá pra desfazer.';

  @override
  String get categoriesDeleted => 'Categoria excluída';

  @override
  String get categoriesNew => 'Nova categoria';

  @override
  String get categoriesEdit => 'Editar categoria';

  @override
  String get commonPreview => 'Preview';

  @override
  String get commonName => 'Nome';

  @override
  String get categoriesParent => 'Categoria pai';

  @override
  String get categoriesNoParent => 'Sem pai';

  @override
  String get categoriesColor => 'Cor';

  @override
  String get categoriesIcon => 'Ícone';

  @override
  String get commonNameRequired => 'Nome obrigatório';

  @override
  String get dashboardMainAccounts => 'Contas principais';

  @override
  String get dashboardMainAccountsDesc => 'As que você mais usa no dia a dia';

  @override
  String get dashboardMainAccountsInfoTitle => 'Contas principais';

  @override
  String get dashboardMainAccountsInfoBody =>
      'Mostramos as contas com mais movimentos neste mês.';

  @override
  String get transactionsManageFixed => 'Gerenciar contas fixas';

  @override
  String get transactionsPendingTitle => 'Transações Pendentes';

  @override
  String get transactionsGroup => 'Agrupar por:';

  @override
  String get transactionsGroupCategory => 'Categoria';

  @override
  String get transactionsGroupRecurrence => 'Recorrência';

  @override
  String get transactionsFilterAllAccounts => 'Todas as contas';

  @override
  String get transactionsFilterAllCategories => 'Todas as categorias';

  @override
  String get transactionsFilterAllStatus => 'Todos';

  @override
  String get transactionsFilterPending => 'Pendente';

  @override
  String get transactionsFilterConfirmed => 'Confirmado';

  @override
  String get transactionsDeleteTitle => 'Excluir transação?';

  @override
  String get transactionsDeleteDesc => 'Essa ação não pode ser desfeita.';

  @override
  String get transactionsConfirmAll => 'Confirmar tudo';

  @override
  String get transactionsLabelAccount => 'Conta';

  @override
  String get transactionsLabelCategory => 'Categoria';

  @override
  String get transactionsLabelStatus => 'Status';

  @override
  String get transactionsLabelEntryAccount => 'Conta de Entrada';

  @override
  String get transactionsLabelCategoryOptional => 'Categoria (Opcional)';

  @override
  String get transactionsLabelSource => 'De (Origem)';

  @override
  String get transactionTypeTransfer => 'Transferência';

  @override
  String get transactionFormTitleNew => 'Nova Transação';

  @override
  String get transactionFormTitleEdit => 'Editar Transação';

  @override
  String get transactionFormLabelDate => 'Data';

  @override
  String get transactionFormLabelNote => 'Observação';

  @override
  String get transactionFormLabelTags => 'Tags (separadas por vírgula)';

  @override
  String get transactionFormSave => 'Salvar';

  @override
  String get transactionFormErrorSave => 'Erro ao salvar';

  @override
  String get transactionFormSuccessSave => 'Transação salva!';

  @override
  String get transactionFormConfirmDelete => 'Excluir transação?';

  @override
  String get transactionFormConfirmConversion => 'Confirmar conversão';

  @override
  String get transactionFormLabelYouSend => 'Você envia:';

  @override
  String get transactionFormLabelYouReceive => 'Você recebe:';

  @override
  String transactionFormEffectiveRate(
    String fromCurrency,
    String toCurrency,
    String rate,
  ) {
    return 'Taxa efetiva: 1 $fromCurrency ≈ $toCurrency $rate';
  }

  @override
  String get transactionFormChangeAccountTitle => 'Alterar contas?';

  @override
  String get transactionFormChangeAccountDesc =>
      'Isso pode mudar a moeda e limpar os valores informados.';

  @override
  String get transactionFormChangeAccountConfirm => 'Alterar e limpar';

  @override
  String get transactionFormTypeExpense => 'Despesa';

  @override
  String get transactionFormTypeIncome => 'Receita';

  @override
  String get transactionFormTypeTransfer => 'Transf.';

  @override
  String get transactionFormMsgRecurringError =>
      'Transação salva, mas não foi possível criar a recorrência.';

  @override
  String get transactionFormMsgRecurringSuccess =>
      'Transação salva e recorrência criada!';

  @override
  String get transactionFormRecurringConfirm => 'Confirmar conta fixa';

  @override
  String get commonConfirm => 'Confirmar';

  @override
  String get commonContinue => 'Continuar';

  @override
  String get accountsTitle => 'Contas';

  @override
  String get accountsWarningCurrency => 'Moedas precisam de revisão';

  @override
  String get accountsWarningCurrencyDesc =>
      'Algumas contas estão com moeda inválida e podem causar valores errados no dashboard.';

  @override
  String get accountsFixCurrency => 'Corrigir agora';

  @override
  String get accountsActive => 'Contas ativas';

  @override
  String get accountsDeleteTitle => 'Excluir conta?';

  @override
  String get accountsDeleteDesc =>
      'Isso vai excluir a conta e todas as transações vinculadas. Não dá pra desfazer.';

  @override
  String get accountsDeleted => 'Conta excluída';

  @override
  String get accountsNew => 'Nova conta';

  @override
  String get accountsEdit => 'Editar conta';

  @override
  String get accountsTypeMoney => 'Dinheiro';

  @override
  String get accountsTypeBank => 'Banco';

  @override
  String get accountsTypeWallet => 'Carteira';

  @override
  String get accountsTypeBroker => 'Investimentos';

  @override
  String get accountsTypeCard => 'Cartão';

  @override
  String get accountsLabelBank => 'Banco';

  @override
  String get accountsLabelCurrency => 'Moeda';

  @override
  String get accountsLabelCurrencyCode => 'Código da moeda';

  @override
  String get accountsHintCurrencyCode => 'Ex: COP, ARS';

  @override
  String get accountsHelperCurrencyCode =>
      'Use 3-5 letras em maiúsculo. Ex: COP.';

  @override
  String get accountsErrorCurrencyInvalid =>
      'Código inválido. Use 3-5 letras (ex: COP).';

  @override
  String get budgetsTitle => 'Orçamentos';

  @override
  String get budgetsTabGoals => 'Metas';

  @override
  String get budgetsTabFixed => 'Contas fixas';

  @override
  String get budgetsMonthTitle => 'Orçamento do mês';

  @override
  String get budgetsPlanPeriod => 'Plano do período';

  @override
  String get budgetsLabelPlanned => 'Planejado';

  @override
  String get budgetsLabelActual => 'Atual';

  @override
  String get budgetsLabelRemaining => 'Restante';

  @override
  String get budgetsHeaderIncome => 'Receitas planejadas';

  @override
  String get budgetsHeaderExpense => 'Gastos planejados';

  @override
  String get budgetsHeaderBalance => 'Saldo planejado';

  @override
  String get budgetsEmptyTitle => 'Sem orçamento para este mês';

  @override
  String get budgetsEmptyDesc =>
      'Crie um orçamento para planejar seus gastos por categoria.';

  @override
  String get budgetsCreateButton => 'Criar orçamento deste mês';

  @override
  String get budgetsActionRemove => 'Remover do mês';

  @override
  String get budgetsSuccessRemoved =>
      'Categoria removida do orçamento deste mês';

  @override
  String get budgetsRemoveCategory => 'Remover do mês';

  @override
  String get budgetsSaveButton => 'Salvar orçamento';

  @override
  String get budgetsSuccessSaved => 'Orçamento salvo!';

  @override
  String get accountsSuccessCurrencyFixed => 'Moedas corrigidas com sucesso!';

  @override
  String get goalsTitle => 'Metas';

  @override
  String get goalsMyGoals => 'Suas metas';

  @override
  String get goalsNew => 'Nova meta';

  @override
  String get goalsEdit => 'Editar meta';

  @override
  String get goalsCreate => 'Criar meta';

  @override
  String get goalsNameLabel => 'Nome da meta';

  @override
  String get goalsNameHint => 'Ex: Fundo de emergência';

  @override
  String get goalsTargetAmount => 'Valor alvo';

  @override
  String get goalsDetailsOptional => 'Detalhes (opcional)';

  @override
  String get goalsTargetDate => 'Data alvo (opcional)';

  @override
  String get goalsNoDate => 'Sem data';

  @override
  String goalsSuggestedMonthly(Object amount) {
    return 'Sugerido: $amount por mês';
  }

  @override
  String get goalsMonthlyContribution => 'Aporte mensal (opcional)';

  @override
  String get goalsLinkedAccount => 'Conta vinculada (opcional)';

  @override
  String get goalsContributionTitle => 'Registrar aporte';

  @override
  String get goalsContributionValue => 'Valor';

  @override
  String get goalsNoAccounts => 'Você não tem contas ativas.';

  @override
  String get goalsDate => 'Data';

  @override
  String get goalsNoteOptional => 'Nota (opcional)';

  @override
  String get goalsErrorName => 'Falta o nome';

  @override
  String get goalsErrorAmount => 'O valor deve ser maior que 0';

  @override
  String get goalsQuickAddConfigError =>
      'Configure um aporte mensal para usar aporte rápido';

  @override
  String get goalsAccountConfigError =>
      'Configure uma conta para usar aporte rápido';

  @override
  String goalsContributionSuccess(Object amount) {
    return 'Aporte de $amount registrado';
  }

  @override
  String goalsProjectionIdeal(Object amount, Object date) {
    return 'Se guardar $amount/mês, chega em $date.';
  }

  @override
  String goalsProjectionOnTrack(Object amount, Object date) {
    return 'Guardando $amount/mês, chega em $date.';
  }

  @override
  String goalsProjectionOnTrackNoDate(Object amount) {
    return 'Guardando $amount/mês';
  }

  @override
  String goalsProjectionOffTrack(Object amount, Object date) {
    return 'Para chegar em $date, precisa guardar $amount/mês.';
  }

  @override
  String goalsProjectionDateOnly(Object date) {
    return 'Meta $date';
  }

  @override
  String goalsRemaining(Object amount) {
    return 'Restante $amount';
  }

  @override
  String get goalsQuickAdd => 'Aporte rápido';

  @override
  String get goalsCustomize => 'Personalizar';

  @override
  String get goalsViewDetails => 'Ver detalhes';

  @override
  String get debtsTitle => 'Dívidas';

  @override
  String get debtsActiveLiabilities => 'Passivos ativos';

  @override
  String get debtsNew => 'Nova dívida';

  @override
  String get debtsEdit => 'Editar dívida';

  @override
  String get debtsName => 'Nome';

  @override
  String get debtsType => 'Tipo';

  @override
  String get debtsTypeCreditCard => 'Cartão de Crédito';

  @override
  String get debtsTypeLoan => 'Empréstimo';

  @override
  String get debtsTypeOther => 'Outro';

  @override
  String get debtsNoCreditCardAccount =>
      'Você não tem contas do tipo \'Cartão de Crédito\'.';

  @override
  String get debtsCreateCardAccount => 'Criar conta Cartão agora';

  @override
  String get debtsLinkedAccount => 'Conta do cartão (Onde caem as compras)';

  @override
  String get debtsInitialBalance => 'Saldo inicial';

  @override
  String get debtsInitialBalanceCurrent => 'Saldo atual (opcional)';

  @override
  String get debtsInitialBalanceHelper =>
      'Se você já tem saldo a pagar neste cartão hoje, informe aqui. Se não, deixe 0.';

  @override
  String get debtsInitialBalanceWarning =>
      'Saldo inicial não pode ser alterado. Ajuste registrando uma compra/pagamento.';

  @override
  String get debtsNoPayingAccount =>
      'Sem contas bancárias/dinheiro para pagar a fatura.';

  @override
  String get debtsPayingAccount => 'Conta pagadora padrão (Opcional)';

  @override
  String get debtsPayingAccountHelper =>
      'Conta sugerida quando você registrar o pagamento da fatura.';

  @override
  String get debtsDueDate => 'Dia de vencimento';

  @override
  String get debtsDueDateHint => 'Ex: 10';

  @override
  String get debtsDueDateError => 'Entre 1 e 31';

  @override
  String get debtsAdvanced => 'Avançado (opcional)';

  @override
  String get debtsMinimumPayment => 'Mínimo a pagar';

  @override
  String get debtsInterestRate => 'Taxa anual (%)';

  @override
  String get debtsErrorSelectAccount => 'Selecione a conta do cartão';

  @override
  String get debtsErrorNoLinkedAccount =>
      'Esta dívida não tem conta vinculada. Edite a dívida para vincular uma conta do tipo Cartão.';

  @override
  String get debtsQuickAccountTitle => 'Criar conta rápida';

  @override
  String get debtsQuickAccountName => 'Nome da conta';

  @override
  String debtsDueDayLabel(Object day) {
    return 'Vence dia $day';
  }

  @override
  String get debtsCurrentBill => 'Fatura atual:';

  @override
  String get debtsAvailableCredit => 'Crédito disponível:';

  @override
  String get debtsAllPaid => 'Tudo pago 🎉';

  @override
  String get debtsActionCharge => 'Registrar Compra';

  @override
  String get debtsActionPay => 'Pagar fatura';

  @override
  String get debtsDialogPaidTitle => 'Tudo pago ✅';

  @override
  String get debtsDialogPaidBody => 'Você não tem saldo a pagar neste cartão.';

  @override
  String get debtsDialogPaidAction => 'Pagar mesmo assim';

  @override
  String get debtsDialogLinkTitle => 'Conta não vinculada';

  @override
  String get debtsDialogLinkBody =>
      'Para pagar a fatura, você precisa vincular uma conta do tipo \'Cartão de Crédito\' a esta dívida.';

  @override
  String get debtsDialogLinkAction => 'Vincular agora';

  @override
  String get monthSummaryTitle => 'Resumo geral do mês';

  @override
  String get monthSummaryTabCategories => 'Por categoria';

  @override
  String get monthSummaryTabAccounts => 'Por conta';

  @override
  String get monthSummaryTabOtherCurrencies => 'Outras moedas';

  @override
  String get monthSummaryHeaderHelper =>
      'Sem conversão automática. Valores por moeda.';

  @override
  String monthSummaryEmptyPrimary(Object currency) {
    return 'Sem movimentos em $currency neste mês.';
  }

  @override
  String get monthSummarySeeOtherCurrencies => 'Veja em Outras moedas';

  @override
  String monthSummaryTotalSpent(Object currency) {
    return 'Total gastos ($currency):';
  }

  @override
  String get monthSummaryOtherCurrencies => 'Outras moedas (sem conversão):';

  @override
  String get monthSummaryNoAccounts => 'Nenhuma conta encontrada';

  @override
  String get monthSummaryIncome => 'Entradas';

  @override
  String get monthSummaryPayments => 'Pagamentos';

  @override
  String get monthSummaryExpenses => 'Saídas';

  @override
  String get monthSummaryPurchases => 'Compras';

  @override
  String get monthSummaryNetMonth => 'Variação no mês';

  @override
  String get monthSummaryBalanceMonth => 'Saldo do mês';

  @override
  String get monthSummaryViewInvoice => 'Ver fatura/histórico';

  @override
  String get monthSummaryViewTransactions => 'Ver transações';

  @override
  String get monthSummaryNoOtherCurrencies => 'Nenhuma outra moeda movimentada';

  @override
  String get monthSummaryOtherCurrenciesSubtitle =>
      'Os valores abaixo não são convertidos para a moeda principal.';

  @override
  String get monthSummaryNet => 'Líquido';

  @override
  String get authLoginTitle => 'Entrar';

  @override
  String get authContinueGoogle => 'Continuar com Google';

  @override
  String get authContinueApple => 'Continuar com Apple';

  @override
  String get authOr => 'ou';

  @override
  String get authLoginEmail => 'Entrar com e-mail';

  @override
  String get authEmailLabel => 'Email';

  @override
  String get authPasswordLabel => 'Senha';

  @override
  String get authButtonLogin => 'Entrar';

  @override
  String get authButtonRegister => 'Criar conta';

  @override
  String get authLoadingLogin => 'Entrando...';

  @override
  String get authLoadingRegister => 'Criando conta...';

  @override
  String get authSwitchToLogin => 'Já tenho conta';

  @override
  String get authSwitchToRegister => 'Criar nova conta';

  @override
  String get authDisclaimer =>
      'Usamos seu login apenas para acessar sua conta.';

  @override
  String get authRegisterTitle => 'Criar conta';

  @override
  String get authRegisterQuick => 'Registro rápido';

  @override
  String get authRegisterSubtitle => 'Só email e senha. Em menos de 30s.';

  @override
  String get transactionFormErrorCreate => 'Erro ao salvar a transação.';

  @override
  String get transactionFormSuccessUpdate =>
      'Transação atualizada com sucesso!';

  @override
  String transactionFormErrorUpdate(String error) {
    return 'Erro ao salvar: $error';
  }

  @override
  String get transactionFormLabelCardPurchase => 'Compra no cartão';

  @override
  String get transactionFormLabelSource => 'Conta de Saída';

  @override
  String get transactionsLabelDestination => 'Para (Destino)';

  @override
  String get transactionsActionImportCsv => 'Importar CSV';

  @override
  String get transactionFormRecurringError =>
      'Transação salva, mas não foi possível criar a recorrência.';

  @override
  String get transactionFormRecurringSuccess =>
      'Transação salva e recorrência criada!';

  @override
  String recurringSummaryDay(Object day) {
    return 'Todo dia $day';
  }

  @override
  String get navDashboard => 'Início';

  @override
  String get navTransactions => 'Transações';

  @override
  String get navBudgets => 'Orçamentos';

  @override
  String get navSettings => 'Ajustes';

  @override
  String get dashboardShortcutTitle => 'Resumo do mês por categorias';

  @override
  String get dashboardShortcutDesc =>
      'Sem conversão automática.\nToque para ver gastos por moeda e categoria.';

  @override
  String get dashboardQuickActionsTitle => 'Ações rápidas';

  @override
  String get dashboardQuickActionExpense => 'Gasto';

  @override
  String get dashboardQuickActionIncome => 'Receita';

  @override
  String get dashboardQuickActionTransfer => 'Transferir';

  @override
  String get dashboardQuickActionFixed => 'Contas fixas';

  @override
  String get cardLabelCredit => 'CARTÃO';

  @override
  String get cardLabelBalancePay => 'Saldo a pagar';

  @override
  String cardLabelDueDay(Object day) {
    return 'Vence dia $day';
  }

  @override
  String get cardLabelPayments => 'Pagamentos';

  @override
  String get cardLabelPurchases => 'Compras';

  @override
  String get cardLabelIncomes => 'Entradas';

  @override
  String get cardLabelExpenses => 'Saídas';

  @override
  String get cardLabelMonthBalance => 'Saldo do mês';

  @override
  String get cardLabelNoMovements => 'Sem movimentos este mês';

  @override
  String get cardActionView => 'Ver transações';

  @override
  String get debtsSectionTitle => 'Dívidas';

  @override
  String get debtsEmptyState => 'Você ainda não cadastrou dívidas.';

  @override
  String get debtsActionAdd => 'Adicionar dívida';

  @override
  String get debtsActionViewAll => 'Ver dívidas';

  @override
  String get debtsPaidMonth => 'Pago este mês: ';

  @override
  String get debtsTotalToPay => 'Total a pagar';

  @override
  String debtsNextDue(Object date, Object name) {
    return 'Próximo: $date — $name';
  }

  @override
  String get debtsPaymentDisclaimer =>
      'Registra um pagamento (não é cobrança automática).';

  @override
  String get commonUnderstood => 'Entendi';

  @override
  String get dashboardOtherAccountsTitle => 'Outras contas';

  @override
  String get dashboardOtherAccountsDesc =>
      'Contas menos usadas ou sem movimentos no mês';

  @override
  String get dashboardOtherAccountsNoMovements => 'Sem movimentos neste mês';

  @override
  String dashboardOtherAccountsMonthBalance(Object amount) {
    return 'Saldo do mês: $amount';
  }

  @override
  String dashboardOtherAccountsViewAll(Object count) {
    return 'Ver todas ($count)';
  }

  @override
  String get transactionFormLabelInvoicePayment => 'Pagamento de fatura';

  @override
  String get transactionFormLabelCardSourceError =>
      'Cartão não pode ser conta de origem. Use sua conta bancária.';

  @override
  String get transactionFormLabelDebtWarning =>
      'Isso aumenta sua dívida. Não sai do banco agora.';

  @override
  String get transactionFormLabelPaymentValue => 'Valor do pagamento';

  @override
  String get transactionFormHelperPayment => 'Sai do banco e abate na fatura.';

  @override
  String get transactionFormLabelTransferValue => 'Valor';

  @override
  String get transactionFormHelperTransfer =>
      'Valor que sai da origem e entra no destino.';

  @override
  String transactionFormLabelSentValue(String currency) {
    return 'Você envia ($currency)';
  }

  @override
  String get transactionFormHelperSent => 'Valor que sai da conta de origem.';

  @override
  String transactionFormLabelReceivedValue(String currency) {
    return 'Você recebe ($currency)';
  }

  @override
  String get transactionFormHelperReceived =>
      'Valor que entra na conta de destino.';

  @override
  String get transactionFormLabelSelectSourceDest =>
      'Selecione Origem e Destino';

  @override
  String get transactionFormHelperSelectSourceDest =>
      'Escolha as contas para liberar o valor.';

  @override
  String get transactionFormLabelAlreadyCleared => 'Já entrou no saldo?';

  @override
  String get transactionFormStatusCleared => 'Confirmada';

  @override
  String get transactionFormStatusPending => 'Pendente';

  @override
  String get transactionFormHelperStatus =>
      'Se estiver pendente, pode mudar depois.';

  @override
  String get transactionFormLabelMoreOptions => 'Mais opções';

  @override
  String get transactionFormLabelMoreOptionsSubtitle =>
      'Nota, Tags, Recorrência';

  @override
  String get transactionFormLabelMoreOptionsRecurring => 'Recorrente';

  @override
  String get transactionFormLabelRepeat => 'Repetir automaticamente';

  @override
  String get transactionFormHelperRepeat =>
      'Cria uma conta fixa para você não esquecer.';

  @override
  String get transactionFormLabelFrequencyMonthly => 'Mensal';

  @override
  String get transactionFormLabelFrequencyWeekly => 'Semanal';

  @override
  String get transactionFormActionManageFixed => 'Gerenciar contas fixas';

  @override
  String get transactionFormLabelSaveTemplate => 'Salvar como Template';

  @override
  String get transactionFormLabelTemplateName => 'Nome do Template';

  @override
  String get transactionFormActionSaving => 'Salvando...';

  @override
  String get transactionFormValidationSameAccount =>
      'Selecione contas diferentes.';

  @override
  String get transactionFormCategoryPurchase => 'Categoria da compra';

  @override
  String get transactionFormInvoiceSource => 'Cartão (Fatura)';

  @override
  String get transactionFormPaymentSuccess => 'Pagamento de fatura registrado!';

  @override
  String transactionFormPaymentError(String error) {
    return 'Erro ao registrar pagamento: $error';
  }

  @override
  String get transactionFormChargeSuccess => 'Compra registrada!';

  @override
  String transactionFormChargeError(String error) {
    return 'Erro ao salvar compra: $error';
  }

  @override
  String get commonToday => 'Hoje';

  @override
  String get commonYesterday => 'Ontem';

  @override
  String get commonFrom => 'de';

  @override
  String get commonTo => 'para';

  @override
  String get commonNoAccount => 'Sem conta';

  @override
  String get transactionsEmptyState => 'Nenhuma transação encontrada';
}
