// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'Desquadra';

  @override
  String get drawerFastAccess => 'QUICK ACCESS';

  @override
  String get drawerDashboard => 'Dashboard';

  @override
  String get drawerTransactions => 'Transactions';

  @override
  String get drawerBudgets => 'Budgets';

  @override
  String get drawerMonthSummary => 'Category Summary';

  @override
  String get drawerManagement => 'MANAGEMENT';

  @override
  String get drawerCategories => 'Categories';

  @override
  String get drawerAccounts => 'Accounts';

  @override
  String get drawerSettings => 'SETTINGS';

  @override
  String get drawerAccount => 'ACCOUNT';

  @override
  String get drawerLogout => 'Logout';

  @override
  String get settingsTitle => 'Settings';

  @override
  String get settingsManageShortcutTitle => 'Manage';

  @override
  String get settingsManageShortcutDesc => 'Categories, Accounts, Goals';

  @override
  String get settingsManageShortcutButton => 'Open Menu';

  @override
  String get drawerDebts => 'Debts';

  @override
  String get drawerGoals => 'Goals';

  @override
  String get drawerRecurring => 'Fixed Expenses';

  @override
  String get settingsPreferences => 'Preferences';

  @override
  String get settingsMainCurrency => 'Main Currency';

  @override
  String get settingsMainCurrencyDesc =>
      'The Month Summary uses only this currency. Other currencies appear in accounts (without conversion).';

  @override
  String get settingsCountry => 'Country';

  @override
  String get settingsCountryDesc =>
      'We use your country to show relevant banks.';

  @override
  String get settingsCountryPlaceholder => 'Select your country';

  @override
  String get settingsAutomation => 'Automation';

  @override
  String get settingsAutoGenerate => 'Auto-generate';

  @override
  String get settingsAutoGenerateDesc =>
      'Creates recurring entries at the start of the month (does not move money).';

  @override
  String get settingsAutoGenerateInfo =>
      'Transactions will be created as pending on the expected date.';

  @override
  String get settingsVersion => 'Version';

  @override
  String get commonCancel => 'Cancel';

  @override
  String get commonSave => 'Save';

  @override
  String get currencyOther => 'Other';

  @override
  String get currencyCustomLabel => 'Code (e.g. COP)';

  @override
  String get currencyCustomHint => '3-5 uppercase letters';

  @override
  String get currencyInvalid => 'Invalid code. Use 3-5 letters (A-Z).';

  @override
  String get settingsAccountSection => 'Account';

  @override
  String get successSettingsUpdate => 'Settings saved successfully!';

  @override
  String errorSettingsUpdate(String error) {
    return 'Error updating settings: $error';
  }

  @override
  String settingsVersionValue(String version) {
    return 'Version $version';
  }

  @override
  String get appTagline => 'Simple finances, without complication.';

  @override
  String drawerMainCurrency(String currency) {
    return 'Main currency: $currency';
  }

  @override
  String get settingsLanguage => 'Language';

  @override
  String get languageEnglish => 'English';

  @override
  String get languagePortuguese => 'Portuguese';

  @override
  String get languageSpanish => 'Spanish';

  @override
  String get onboardingFeature1 => '• Register expense in 3 taps';

  @override
  String get onboardingFeature2 => '• See real and planned balance';

  @override
  String get onboardingFeature3 => '• Everything in one place, no jargon';

  @override
  String get onboardingStartFast => 'Start Fast';

  @override
  String get commonSkip => 'Skip';

  @override
  String get onboardingWelcome => 'Welcome!';

  @override
  String get onboardingDescription =>
      'Let\'s get everything ready in less than 60 seconds.';

  @override
  String get onboardingUseExamples => 'I want to use examples';

  @override
  String get onboardingSkipDescription => 'You can skip and adjust later.';

  @override
  String get onboardingCreateAccount =>
      'We will create an account for you to track expenses.';

  @override
  String get onboardingChooseCreation => 'Choose what to create now.';

  @override
  String get onboardingCreateBudget => 'Create base budget';

  @override
  String get onboardingCreateBudgetDesc => 'You can edit later.';

  @override
  String get onboardingFirstTransaction =>
      'You can already register your first expense.';

  @override
  String get onboardingAddCards => 'Add your cards to control invoices.';

  @override
  String get commonDelete => 'Delete';

  @override
  String get transactionTypeExpense => 'Expense';

  @override
  String get transactionTypeIncome => 'Income';

  @override
  String get commonActive => 'Active';

  @override
  String get recurringTitle => 'Recurring';

  @override
  String get recurringMyRules => 'My Rules';

  @override
  String get recurringOpenPlanner => 'Open Planner';

  @override
  String recurringPendingItems(int count) {
    return 'You have $count items to confirm.';
  }

  @override
  String get commonView => 'View';

  @override
  String get commonEdit => 'Edit';

  @override
  String get recurringPlanMonth => 'Plan Month';

  @override
  String get recurringGeneratedEntries => 'Generated Entries';

  @override
  String get commonBack => 'Back';

  @override
  String get commonNext => 'Next';

  @override
  String get commonFinish => 'Finish';

  @override
  String get onboardingMainAccount => 'Main Account';

  @override
  String get accountNameLabel => 'Account Name';

  @override
  String get accountTypeLabel => 'Type';

  @override
  String get accountTypeBank => 'Bank';

  @override
  String get accountTypeCash => 'Cash';

  @override
  String get accountTypeWallet => 'Wallet';

  @override
  String get onboardingBaseCategories => 'Base Categories';

  @override
  String get onboardingAllSet => 'All Set';

  @override
  String get onboardingExamplesCreated =>
      'We created basic examples for you to adjust later.';

  @override
  String get onboardingMinimumCreated =>
      'We created the minimum for you to start.';

  @override
  String get onboardingCreditCards => 'Credit Cards';

  @override
  String get onboardingCardName => 'Card Name';

  @override
  String get onboardingNoCards =>
      'No cards added. Click + to add or Next to skip.';

  @override
  String get recurringAppDescription =>
      'The app only records. It does not charge.';

  @override
  String get commonNew => 'New';

  @override
  String get recurringInactive => 'Inactive';

  @override
  String get recurringNewRule => 'New Recurring Rule';

  @override
  String get recurringEmptyState =>
      'Create a recurring rule to plan your month in seconds.';

  @override
  String recurringFrequencyMonthly(int day) {
    return 'Every month on day $day';
  }

  @override
  String get recurringFrequencyWeekly => 'Weekly';

  @override
  String get recurringFrequencyYearly => 'Yearly';

  @override
  String get commonComingSoon => 'Coming Soon';

  @override
  String get commonPause => 'Pause';

  @override
  String get commonActivate => 'Activate';

  @override
  String get recurringDeleteTitle => 'Delete rule?';

  @override
  String get recurringDeleteDesc =>
      'This does not delete already generated entries.';

  @override
  String get recurringPlanMonthDesc => 'Generate monthly entries from rules.';

  @override
  String get recurringPendingConfirmation => 'Pending Confirmation';

  @override
  String recurringGeneratedSuccess(int count) {
    return 'Generated $count entries!';
  }

  @override
  String recurringGeneratedDialogBody(int count) {
    return '$count entries were created as pending.';
  }

  @override
  String get commonStay => 'Stay here';

  @override
  String get recurringGoToConfirm => 'Go to confirm';

  @override
  String get commonErrorGenerating => 'Error generating';

  @override
  String get recurringNonePlanned => 'No recurrence planned for this month.';

  @override
  String recurringGenerateButton(int count) {
    return 'Generate entries ($count)';
  }

  @override
  String get recurringStatusToGenerate => 'To generate';

  @override
  String get recurringStatusGenerated => 'Generated';

  @override
  String get recurringStatusIgnored => 'Ignored';

  @override
  String get commonNoDescription => 'No description';

  @override
  String get recurringChipGenerated => 'Generated';

  @override
  String get recurringRestoreTooltip => 'Restore (Include in generation)';

  @override
  String get recurringIgnoreTooltip => 'Ignore (Do not generate)';

  @override
  String recurringMissingGenerated(int count) {
    return '$count entries missing to generate';
  }

  @override
  String get recurringViewPending => 'View pending';

  @override
  String get recurringViewRules => 'View rules';

  @override
  String get recurringNoRulesYet => 'You don\'t have recurring rules yet';

  @override
  String get recurringCreateFirst => 'Create first';

  @override
  String get categoriesActive => 'Active Categories';

  @override
  String get categoriesDeleteTitle => 'Delete category?';

  @override
  String get categoriesDeleteDesc =>
      'This will delete the category and all linked transactions. Cannot be undone.';

  @override
  String get categoriesDeleted => 'Category deleted';

  @override
  String get categoriesNew => 'New category';

  @override
  String get categoriesEdit => 'Edit category';

  @override
  String get commonPreview => 'Preview';

  @override
  String get commonName => 'Name';

  @override
  String get categoriesParent => 'Parent category';

  @override
  String get categoriesNoParent => 'No parent';

  @override
  String get categoriesColor => 'Color';

  @override
  String get categoriesIcon => 'Icon';

  @override
  String get commonNameRequired => 'Name required';

  @override
  String get dashboardMainAccounts => 'Main Accounts';

  @override
  String get dashboardMainAccountsDesc => 'The ones you use most deeply';

  @override
  String get dashboardMainAccountsInfoTitle => 'Main Accounts';

  @override
  String get dashboardMainAccountsInfoBody =>
      'We show accounts with most movement this month.';

  @override
  String get transactionsManageFixed => 'Manage Fixed Expenses';

  @override
  String get transactionsPendingTitle => 'Pending Transactions';

  @override
  String get transactionsGroup => 'Group by:';

  @override
  String get transactionsGroupCategory => 'Category';

  @override
  String get transactionsGroupRecurrence => 'Recurrence';

  @override
  String get transactionsFilterAllAccounts => 'All accounts';

  @override
  String get transactionsFilterAllCategories => 'All categories';

  @override
  String get transactionsFilterAllStatus => 'All';

  @override
  String get transactionsFilterPending => 'Pending';

  @override
  String get transactionsFilterConfirmed => 'Confirmed';

  @override
  String get transactionsDeleteTitle => 'Delete transaction?';

  @override
  String get transactionsDeleteDesc => 'This action cannot be undone.';

  @override
  String get transactionsConfirmAll => 'Confirm all';

  @override
  String get transactionsLabelAccount => 'Account';

  @override
  String get transactionsLabelCategory => 'Category';

  @override
  String get transactionsLabelStatus => 'Status';

  @override
  String get transactionsLabelEntryAccount => 'Entry Account';

  @override
  String get transactionsLabelCategoryOptional => 'Category (Optional)';

  @override
  String get transactionsLabelSource => 'From (Source)';

  @override
  String get transactionTypeTransfer => 'Transfer';

  @override
  String get transactionFormTitleNew => 'New Transaction';

  @override
  String get transactionFormTitleEdit => 'Edit Transaction';

  @override
  String get transactionFormLabelDate => 'Date';

  @override
  String get transactionFormLabelNote => 'Note';

  @override
  String get transactionFormLabelTags => 'Tags (comma separated)';

  @override
  String get transactionFormSave => 'Save';

  @override
  String get transactionFormErrorSave => 'Error saving';

  @override
  String get transactionFormSuccessSave => 'Transaction saved!';

  @override
  String get transactionFormConfirmDelete => 'Delete transaction?';

  @override
  String get transactionFormConfirmConversion => 'Confirm conversion';

  @override
  String get transactionFormLabelYouSend => 'You send:';

  @override
  String get transactionFormLabelYouReceive => 'You receive:';

  @override
  String transactionFormEffectiveRate(
    String fromCurrency,
    String toCurrency,
    String rate,
  ) {
    return 'Effective rate: 1 $fromCurrency ≈ $toCurrency $rate';
  }

  @override
  String get transactionFormChangeAccountTitle => 'Change accounts?';

  @override
  String get transactionFormChangeAccountDesc =>
      'This may change the currency and clear entered values.';

  @override
  String get transactionFormChangeAccountConfirm => 'Change and clear';

  @override
  String get transactionFormTypeExpense => 'Expense';

  @override
  String get transactionFormTypeIncome => 'Income';

  @override
  String get transactionFormTypeTransfer => 'Transf.';

  @override
  String get transactionFormMsgRecurringError =>
      'Transaction saved, but recurrence could not be created.';

  @override
  String get transactionFormMsgRecurringSuccess =>
      'Transaction saved and recurrence created!';

  @override
  String get transactionFormRecurringConfirm => 'Confirm recurring';

  @override
  String get commonConfirm => 'Confirm';

  @override
  String get commonContinue => 'Continue';

  @override
  String get accountsTitle => 'Accounts';

  @override
  String get accountsWarningCurrency => 'Currencies need review';

  @override
  String get accountsWarningCurrencyDesc =>
      'Some accounts have invalid currency and may cause wrong values in dashboard.';

  @override
  String get accountsFixCurrency => 'Fix now';

  @override
  String get accountsActive => 'Active Accounts';

  @override
  String get accountsCardsSection => 'Cards';

  @override
  String get accountsCardChip => 'CARD';

  @override
  String get accountsCardCurrentBill => 'Current bill';

  @override
  String get accountsCardViewDebts => 'View in Debts';

  @override
  String get accountsDeleteTitle => 'Delete account?';

  @override
  String get accountsDeleteDesc =>
      'This will delete the account and all linked transactions. Cannot be undone.';

  @override
  String get accountsDeleted => 'Account deleted';

  @override
  String get accountsNew => 'New Account';

  @override
  String get accountsEdit => 'Edit Account';

  @override
  String get accountsTypeMoney => 'Cash';

  @override
  String get accountsTypeBank => 'Bank';

  @override
  String get accountsTypeWallet => 'Wallet';

  @override
  String get accountsTypeBroker => 'Investments';

  @override
  String get accountsTypeCard => 'Credit Card';

  @override
  String get accountsLabelBank => 'Bank';

  @override
  String get accountsLabelCurrency => 'Currency';

  @override
  String get accountsLabelCurrencyCode => 'Currency Code';

  @override
  String get accountsHintCurrencyCode => 'Ex: COP, ARS';

  @override
  String get accountsHelperCurrencyCode =>
      'Use 3-5 uppercase letters. Ex: COP.';

  @override
  String get accountsErrorCurrencyInvalid =>
      'Invalid code. Use 3-5 letters (e.g. COP).';

  @override
  String get budgetsTitle => 'Budgets';

  @override
  String get budgetsTabGoals => 'Goals';

  @override
  String get budgetsTabFixed => 'Fixed Expenses';

  @override
  String get budgetsMonthTitle => 'Monthly Budget';

  @override
  String get budgetsPlanPeriod => 'Period Plan';

  @override
  String get budgetsPlanTitle => 'Month plan';

  @override
  String get budgetsPlanSubtitle =>
      'Log what you plan to spend or receive this month.';

  @override
  String get budgetsPlanTypeExpense => 'Expense';

  @override
  String get budgetsPlanTypeIncome => 'Income';

  @override
  String get budgetsPlanCategoryLabel => 'Category';

  @override
  String get budgetsPlanAmountLabel => 'Amount';

  @override
  String get budgetsPlanDescriptionLabel => 'Description (optional)';

  @override
  String get budgetsPlanAddAction => 'Add';

  @override
  String get budgetsPlanOnboardingTitle => 'Create your monthly budget';

  @override
  String get budgetsPlanOnboardingSubtitle =>
      'Add what you plan to spend or receive. You can adjust later.';

  @override
  String get budgetsPlanOnboardingNote =>
      'It doesn\'t move money. It\'s just a plan.';

  @override
  String get budgetsPlanSectionTitle => 'Your plan by category';

  @override
  String get budgetsPlanEmptyTitle =>
      'You don\'t have a plan for this month yet.';

  @override
  String get budgetsPlanEmptyHelper =>
      'Start with 1 expense or 1 income. You can refine later.';

  @override
  String get budgetsPlanEmptyAction => 'Add first entry';

  @override
  String get budgetsPlanEmptyLink => 'Add entry';

  @override
  String get budgetsPlanEntryAddedToast => 'Done. Added to your monthly plan.';

  @override
  String get budgetsPlanPlannedExpense => 'Planned (expenses)';

  @override
  String get budgetsPlanPlannedIncome => 'Planned (income)';

  @override
  String get budgetsPlanDetailsAction => 'View details';

  @override
  String budgetsPlanCategoryDetailTitle(Object category) {
    return 'Details for $category';
  }

  @override
  String get budgetsPlanAddAnotherAction => 'Add another';

  @override
  String get budgetsPlanEmptyCategoryDetail =>
      'No entries for this category yet.';

  @override
  String get budgetsSnapshotTitle => 'We used last month\'s plan as a base.';

  @override
  String get budgetsSnapshotSubtitle => 'Apply it or start from zero.';

  @override
  String get budgetsSnapshotApplyAction => 'Use last month as a base';

  @override
  String get budgetsSnapshotNotFound =>
      'We couldn\'t find a previous plan to use as a base.';

  @override
  String get budgetsSnapshotStartFreshAction => 'Start from zero';

  @override
  String get budgetsSegmentCategories => 'Categories';

  @override
  String get budgetsSegmentDebts => 'Debts';

  @override
  String get budgetsSegmentSummary => 'Summary';

  @override
  String get budgetsLabelPlanned => 'Budget';

  @override
  String get budgetsLabelActual => 'Spent';

  @override
  String get budgetsLabelActualIncome => 'Received';

  @override
  String get budgetsLabelRemaining => 'Remaining';

  @override
  String budgetsCategoryStatusRemaining(Object value) {
    return 'You have $value left';
  }

  @override
  String budgetsCategoryIncomeStatusRemaining(Object value) {
    return 'You are $value short';
  }

  @override
  String get budgetsCategoryStatusAtLimit => 'Limit reached';

  @override
  String get budgetsCategoryIncomeStatusAtLimit => 'Goal reached';

  @override
  String budgetsCategoryStatusNearLimit(Object value) {
    return 'Near the limit — $value left';
  }

  @override
  String budgetsCategoryIncomeStatusNearLimit(Object value) {
    return 'Near the goal — $value to go';
  }

  @override
  String budgetsCategoryStatusOver(Object value) {
    return 'You went over by $value';
  }

  @override
  String budgetsCategoryIncomeStatusOver(Object value) {
    return 'You exceeded by $value';
  }

  @override
  String get budgetsCategoryStatusOverHelper =>
      'You can adjust the budget or reduce spending in this category.';

  @override
  String get budgetsHeaderIncome => 'Planned Income';

  @override
  String get budgetsHeaderExpense => 'Planned Expenses';

  @override
  String get budgetsHeaderBalance => 'Planned Balance';

  @override
  String get budgetsEmptyTitle => 'You haven\'t set any budgets yet.';

  @override
  String get budgetsEmptyDesc => 'Start with your main categories.';

  @override
  String get budgetsCreateButton => 'Set budgets';

  @override
  String get budgetsActionRemove => 'Remove from month';

  @override
  String get budgetsSuccessRemoved =>
      'Category removed from this month\'s budget';

  @override
  String get budgetsRemoveCategory => 'Remove from month';

  @override
  String get budgetsSaveButton => 'Save Budget';

  @override
  String get budgetsSaveCategoriesButton => 'Save monthly plan';

  @override
  String get budgetsSaveDebtsButton => 'Save payment plan';

  @override
  String get budgetsSuccessSaved => 'All set. Your month plan was saved.';

  @override
  String get budgetsMonthSummaryTitle => 'Month summary';

  @override
  String get budgetsMonthSummaryPlannedCategories =>
      'Planned spending (categories)';

  @override
  String get budgetsMonthSummaryPlannedDebts => 'Planned debt payments';

  @override
  String get budgetsMonthSummaryTotalOutflow => 'Total planned outflow';

  @override
  String get budgetsMonthSummaryOtherCurrencies =>
      'Other currencies (no conversion)';

  @override
  String get budgetsDebtPlannedTitle => 'Debts (planned payments)';

  @override
  String get budgetsDebtPlannedSubtitle =>
      'Set aside what you\'ll pay this month. It\'s not a new expense.';

  @override
  String get budgetsDebtPaymentNote =>
      'Paying debt isn’t a new expense. It’s paying what you already owe.';

  @override
  String get budgetsDebtPayLabel => 'I will pay';

  @override
  String get budgetsDebtOweLabel => 'I owe';

  @override
  String get budgetsDebtQuickMin => 'Minimum';

  @override
  String get budgetsDebtQuickTotal => 'Total';

  @override
  String get budgetsDebtOverpayWarning =>
      'You\'re paying more than you owe. Are you sure?';

  @override
  String budgetsDebtPaidPlanned(Object paid, Object planned) {
    return 'Paid: $paid / $planned planned';
  }

  @override
  String get budgetsDebtActionZeroAll => 'Set all to 0';

  @override
  String get budgetsDebtActionSuggest => 'Suggest payments';

  @override
  String budgetsDebtOverpaid(Object amount) {
    return 'You paid $amount more than planned.';
  }

  @override
  String budgetsDebtRemaining(Object amount) {
    return '$amount left to reach your plan.';
  }

  @override
  String get budgetsDebtEmptyState => 'You have no debts registered.';

  @override
  String get budgetsDebtMinimumWarning => 'Your plan is below the minimum.';

  @override
  String budgetsDebtTotalPlannedLabel(Object currency) {
    return 'Total planned ($currency)';
  }

  @override
  String get budgetsSummaryCategoriesTitle => 'Spending by category';

  @override
  String get budgetsSummaryDebtsTitle => 'Planned debt payments';

  @override
  String get budgetsSummaryPlanTitle => 'Month overview';

  @override
  String get budgetsSummaryPlannedExpense => 'Planned expenses';

  @override
  String get budgetsSummaryPlannedIncome => 'Planned income';

  @override
  String get budgetsSummaryEstimatedAvailable => 'Estimated available';

  @override
  String get budgetsSummaryPlannedDebts => 'Planned debt payments';

  @override
  String get budgetsSummaryTotalPlanned => 'Total planned';

  @override
  String get budgetsSummaryTotalSpent => 'Total spent';

  @override
  String budgetsSummaryOverspentCount(Object count) {
    return 'Over budget categories: $count';
  }

  @override
  String get budgetsSummaryViewCategories => 'View categories';

  @override
  String get budgetsSummaryViewDebts => 'View debts';

  @override
  String budgetsSummaryNextDueDay(Object day) {
    return 'Next due day: $day';
  }

  @override
  String get budgetsCategoriesTitle => 'Spending by category';

  @override
  String get accountsSuccessCurrencyFixed => 'Currencies fixed successfully!';

  @override
  String get goalsTitle => 'Goals';

  @override
  String get goalsMyGoals => 'My Goals';

  @override
  String get goalsNew => 'New Goal';

  @override
  String get goalsEdit => 'Edit Goal';

  @override
  String get goalsCreate => 'Create Goal';

  @override
  String get goalsNameLabel => 'Goal Name';

  @override
  String get goalsNameHint => 'e.g. Emergency Fund';

  @override
  String get goalsTargetAmount => 'Target Amount';

  @override
  String get goalsDetailsOptional => 'Details (optional)';

  @override
  String get goalsTargetDate => 'Target Date (optional)';

  @override
  String get goalsNoDate => 'No date';

  @override
  String goalsSuggestedMonthly(Object amount) {
    return 'Suggested: $amount per month';
  }

  @override
  String get goalsMonthlyContribution => 'Monthly Contribution (optional)';

  @override
  String get goalsLinkedAccount => 'Linked Account (optional)';

  @override
  String get goalsContributionTitle => 'Log Contribution';

  @override
  String get goalsContributionValue => 'Value';

  @override
  String get goalsNoAccounts => 'You have no active accounts.';

  @override
  String get goalsDate => 'Date';

  @override
  String get goalsNoteOptional => 'Note (optional)';

  @override
  String get goalsErrorName => 'Name required';

  @override
  String get goalsErrorAmount => 'Amount must be greater than 0';

  @override
  String get goalsQuickAddConfigError =>
      'Configure a monthly contribution to use quick add';

  @override
  String get goalsAccountConfigError => 'Configure an account to use quick add';

  @override
  String goalsContributionSuccess(Object amount) {
    return 'Contribution of $amount logged';
  }

  @override
  String goalsProjectionIdeal(Object amount, Object date) {
    return 'Saving $amount/mo, reach by $date.';
  }

  @override
  String goalsProjectionOnTrack(Object amount, Object date) {
    return 'Saving $amount/mo, reach by $date.';
  }

  @override
  String goalsProjectionOnTrackNoDate(Object amount) {
    return 'Saving $amount/mo';
  }

  @override
  String goalsProjectionOffTrack(Object amount, Object date) {
    return 'To reach by $date, need to save $amount/mo.';
  }

  @override
  String goalsProjectionDateOnly(Object date) {
    return 'Goal $date';
  }

  @override
  String goalsRemaining(Object amount) {
    return 'Remaining $amount';
  }

  @override
  String get goalsQuickAdd => 'Quick Add';

  @override
  String get goalsCustomize => 'Customize';

  @override
  String get goalsViewDetails => 'View Details';

  @override
  String get goalsEmptyTitle => 'Your goals start here';

  @override
  String get goalsEmptyDescription =>
      'A goal is a simple target to set money aside little by little. You choose the amount and the date. You can change it later.';

  @override
  String get goalsEmptyBullet1 => '• See what’s left to reach it';

  @override
  String get goalsEmptyBullet2 => '• Track it without complicated math';

  @override
  String get goalsEmptyBullet3 => '• Stay focused on what matters';

  @override
  String get goalsEmptyExamplesTitle => 'Ready ideas (tap to use)';

  @override
  String get goalsEmptyExampleEmergency => 'Emergency buffer';

  @override
  String get goalsEmptyExampleTrip => 'Trip';

  @override
  String get goalsEmptyExampleBigPurchase => 'Big purchase';

  @override
  String get goalsEmptyExampleBillsBuffer => 'Bills buffer';

  @override
  String get goalsEmptyCta => 'Create my first goal';

  @override
  String get goalsEmptyMicrocopy => 'You can edit or delete it later.';

  @override
  String get goalsHelpToggle => 'What is this?';

  @override
  String get debtsTitle => 'Debts';

  @override
  String get debtsActiveLiabilities => 'Active Liabilities';

  @override
  String get debtsNew => 'New Debt';

  @override
  String get debtsEdit => 'Edit Debt';

  @override
  String get debtsName => 'Name';

  @override
  String get debtsType => 'Type';

  @override
  String get debtsTypeCreditCard => 'Credit Card';

  @override
  String get debtsTypeLoan => 'Loan';

  @override
  String get debtsTypeOther => 'Other';

  @override
  String get debtsNoCreditCardAccount =>
      'You have no \'Credit Card\' accounts.';

  @override
  String get debtsCreateCardAccount => 'Create Card Account now';

  @override
  String get debtsLinkedAccount => 'Card Account (Where purchases land)';

  @override
  String get debtsInitialBalance => 'Initial Balance';

  @override
  String get debtsInitialBalanceCurrent => 'Current Balance (Optional)';

  @override
  String get debtsInitialBalanceHelper =>
      'If you have a balance to pay today, enter here. Else leave 0.';

  @override
  String get debtsInitialBalanceWarning =>
      'Initial balance cannot be changed. Adjust by logging a purchase/payment.';

  @override
  String get debtsNoPayingAccount => 'No bank/cash accounts to pay the bill.';

  @override
  String get debtsPayingAccount => 'Default Paying Account (Optional)';

  @override
  String get debtsPayingAccountHelper =>
      'Suggested account when paying the bill.';

  @override
  String get debtsDueDate => 'Due Day';

  @override
  String get debtsDueDateHint => 'e.g. 10';

  @override
  String get debtsDueDateError => 'Between 1 and 31';

  @override
  String get debtsAdvanced => 'Advanced (Optional)';

  @override
  String get debtsMinimumPayment => 'Minimum Payment';

  @override
  String get debtsInterestRate => 'Annual Rate (%)';

  @override
  String get debtsErrorSelectAccount => 'Select card account';

  @override
  String get debtsErrorNoLinkedAccount =>
      'This debt has no linked account. Edit to link a Credit Card account.';

  @override
  String get debtsQuickAccountTitle => 'Create Quick Account';

  @override
  String get debtsQuickAccountName => 'Account Name';

  @override
  String debtsDueDayLabel(Object day) {
    return 'Due day $day';
  }

  @override
  String get debtsCurrentBill => 'Current Bill:';

  @override
  String get debtsAvailableCredit => 'Available Credit:';

  @override
  String get debtsAllPaid => 'All Paid 🎉';

  @override
  String get debtsActionCharge => 'Log Purchase';

  @override
  String get debtsActionPay => 'Pay Bill';

  @override
  String get debtsDialogPaidTitle => 'All Paid ✅';

  @override
  String get debtsDialogPaidBody => 'You have no balance to pay on this card.';

  @override
  String get debtsDialogPaidAction => 'Pay anyway';

  @override
  String get debtsDialogLinkTitle => 'Account Not Linked';

  @override
  String get debtsDialogLinkBody =>
      'To pay the bill, you need to link a \'Credit Card\' account to this debt.';

  @override
  String get debtsDialogLinkAction => 'Link Now';

  @override
  String get monthSummaryTitle => 'Month Summary';

  @override
  String get monthSummaryTabCategories => 'By Category';

  @override
  String get monthSummaryTabAccounts => 'By Account';

  @override
  String get monthSummaryTabOtherCurrencies => 'Other Currencies';

  @override
  String get monthSummaryHeaderHelper =>
      'No automatic conversion. Values by currency.';

  @override
  String monthSummaryEmptyPrimary(Object currency) {
    return 'No movements in $currency this month.';
  }

  @override
  String get monthSummarySeeOtherCurrencies => 'See Other Currencies';

  @override
  String monthSummaryTotalSpent(Object currency) {
    return 'Total spent ($currency):';
  }

  @override
  String get monthSummaryOtherCurrencies => 'Other currencies (no conversion):';

  @override
  String get monthSummaryNoAccounts => 'No accounts found';

  @override
  String get monthSummaryIncome => 'Income';

  @override
  String get monthSummaryPayments => 'Payments';

  @override
  String get monthSummaryExpenses => 'Expenses';

  @override
  String get monthSummaryPurchases => 'Purchases';

  @override
  String get monthSummaryNetMonth => 'Month Net';

  @override
  String get monthSummaryBalanceMonth => 'Month Balance';

  @override
  String get monthSummaryViewInvoice => 'View Invoice/History';

  @override
  String get monthSummaryViewTransactions => 'View Transactions';

  @override
  String get monthSummaryNoOtherCurrencies => 'No other currencies moved';

  @override
  String get monthSummaryOtherCurrenciesSubtitle =>
      'Values below are not converted to main currency.';

  @override
  String get monthSummaryNet => 'Net';

  @override
  String get authLoginTitle => 'Log In';

  @override
  String get authContinueGoogle => 'Continue with Google';

  @override
  String get authContinueApple => 'Continue with Apple';

  @override
  String get authOr => 'or';

  @override
  String get authLoginEmail => 'Login with email';

  @override
  String get authEmailLabel => 'Email';

  @override
  String get authPasswordLabel => 'Password';

  @override
  String get authButtonLogin => 'Log In';

  @override
  String get authButtonRegister => 'Create Account';

  @override
  String get authLoadingLogin => 'Logging in...';

  @override
  String get authLoadingRegister => 'Creating account...';

  @override
  String get authSwitchToLogin => 'I have an account';

  @override
  String get authSwitchToRegister => 'Create new account';

  @override
  String get authDisclaimer => 'We use your login only to access your account.';

  @override
  String get authRegisterTitle => 'Create Account';

  @override
  String get authRegisterQuick => 'Quick Register';

  @override
  String get authRegisterSubtitle => 'Only email and password. < 30s.';

  @override
  String get transactionFormErrorCreate => 'Error saving transaction.';

  @override
  String get transactionFormSuccessUpdate =>
      'Transaction updated successfully!';

  @override
  String transactionFormErrorUpdate(String error) {
    return 'Error saving: $error';
  }

  @override
  String get transactionFormLabelCardPurchase => 'Card Purchase';

  @override
  String get transactionFormLabelSource => 'Source Account';

  @override
  String get transactionsLabelDestination => 'To (Destination)';

  @override
  String get transactionsActionImportCsv => 'Import CSV';

  @override
  String get transactionFormRecurringError =>
      'Transaction saved, but recurrence could not be created.';

  @override
  String get transactionFormRecurringSuccess =>
      'Transaction saved and recurrence created!';

  @override
  String recurringSummaryDay(Object day) {
    return 'Monthly on day $day';
  }

  @override
  String get navDashboard => 'Home';

  @override
  String get navTransactions => 'Transactions';

  @override
  String get navBudgets => 'Budgets';

  @override
  String get navSettings => 'Settings';

  @override
  String get dashboardShortcutTitle => 'Category Monthly Summary';

  @override
  String get dashboardShortcutDesc =>
      'No auto-conversion.\nTap to see expenses by currency and category.';

  @override
  String get dashboardQuickActionsTitle => 'Quick Actions';

  @override
  String get dashboardQuickActionExpense => 'Expense';

  @override
  String get dashboardQuickActionIncome => 'Income';

  @override
  String get dashboardQuickActionTransfer => 'Transfer';

  @override
  String get dashboardQuickActionFixed => 'Fixed Bills';

  @override
  String get cardLabelCredit => 'CARD';

  @override
  String get cardLabelBalancePay => 'Balance Due';

  @override
  String cardLabelDueDay(Object day) {
    return 'Due day $day';
  }

  @override
  String get cardLabelPayments => 'Payments';

  @override
  String get cardLabelPurchases => 'Purchases';

  @override
  String get cardLabelIncomes => 'Incomes';

  @override
  String get cardLabelExpenses => 'Expenses';

  @override
  String get cardLabelMonthBalance => 'Month Balance';

  @override
  String get cardLabelNoMovements => 'No movements this month';

  @override
  String get cardActionView => 'View transactions';

  @override
  String get debtsSectionTitle => 'Debts';

  @override
  String get debtsEmptyState => 'You have not registered any debts.';

  @override
  String get debtsActionAdd => 'Add Debt';

  @override
  String get debtsActionViewAll => 'View Debts';

  @override
  String get debtsPaidMonth => 'Paid this month: ';

  @override
  String get debtsTotalToPay => 'Total to pay';

  @override
  String debtsNextDue(Object date, Object name) {
    return 'Next: $date — $name';
  }

  @override
  String get debtsPaymentDisclaimer =>
      'Registers a payment (not an automatic charge).';

  @override
  String get commonUnderstood => 'Understood';

  @override
  String get dashboardOtherAccountsTitle => 'Other accounts';

  @override
  String get dashboardOtherAccountsDesc =>
      'Less used accounts or no movements this month';

  @override
  String get dashboardOtherAccountsNoMovements => 'No movements this month';

  @override
  String dashboardOtherAccountsMonthBalance(Object amount) {
    return 'Month balance: $amount';
  }

  @override
  String dashboardOtherAccountsViewAll(Object count) {
    return 'View all ($count)';
  }

  @override
  String get transactionFormLabelInvoicePayment => 'Invoice Payment';

  @override
  String get transactionFormLabelCardSourceError =>
      'Card cannot be source account. Use your bank account.';

  @override
  String get transactionFormLabelDebtWarning =>
      'This increases your debt. It does not leave your bank now.';

  @override
  String get transactionFormLabelPaymentValue => 'Payment Value';

  @override
  String get transactionFormHelperPayment =>
      'Leaves bank and deducts from invoice.';

  @override
  String get transactionFormLabelTransferValue => 'Value';

  @override
  String get transactionFormHelperTransfer =>
      'Value leaving source and entering destination.';

  @override
  String transactionFormLabelSentValue(String currency) {
    return 'You send ($currency)';
  }

  @override
  String get transactionFormHelperSent => 'Value leaving source account.';

  @override
  String transactionFormLabelReceivedValue(String currency) {
    return 'You receive ($currency)';
  }

  @override
  String get transactionFormHelperReceived =>
      'Value entering destination account.';

  @override
  String get transactionFormLabelSelectSourceDest =>
      'Select Source and Destination';

  @override
  String get transactionFormHelperSelectSourceDest =>
      'Choose accounts to release value.';

  @override
  String get transactionFormLabelAlreadyCleared => 'Already cleared?';

  @override
  String get transactionFormStatusCleared => 'Confirmed';

  @override
  String get transactionFormStatusPending => 'Pending';

  @override
  String get transactionFormHelperStatus => 'If pending, you can change later.';

  @override
  String get transactionFormLabelMoreOptions => 'More options';

  @override
  String get transactionFormLabelMoreOptionsSubtitle =>
      'Note, Tags, Recurrence';

  @override
  String get transactionFormLabelMoreOptionsRecurring => 'Recurring';

  @override
  String get transactionFormLabelRepeat => 'Repeat automatically';

  @override
  String get transactionFormHelperRepeat =>
      'Create a fixed expense so you don\'t forget.';

  @override
  String get transactionFormLabelFrequencyMonthly => 'Monthly';

  @override
  String get transactionFormLabelFrequencyWeekly => 'Weekly';

  @override
  String get transactionFormActionManageFixed => 'Manage fixed expenses';

  @override
  String get transactionFormLabelSaveTemplate => 'Save as Template';

  @override
  String get transactionFormLabelTemplateName => 'Template Name';

  @override
  String get transactionFormActionSaving => 'Saving...';

  @override
  String get transactionFormValidationSameAccount =>
      'Select different accounts.';

  @override
  String get transactionFormCategoryPurchase => 'Purchase Category';

  @override
  String get transactionFormInvoiceSource => 'Card (Invoice)';

  @override
  String get transactionFormPaymentSuccess => 'Invoice payment registered!';

  @override
  String transactionFormPaymentError(String error) {
    return 'Error registering payment: $error';
  }

  @override
  String get transactionFormChargeSuccess => 'Purchase registered!';

  @override
  String transactionFormChargeError(String error) {
    return 'Error saving purchase: $error';
  }

  @override
  String get commonToday => 'Today';

  @override
  String get commonYesterday => 'Yesterday';

  @override
  String get commonFrom => 'from';

  @override
  String get commonTo => 'to';

  @override
  String get commonNoAccount => 'No account';

  @override
  String get transactionsEmptyState => 'No transactions found';

  @override
  String get onboardingPreferencesTitle => 'Preferences';

  @override
  String get onboardingPreferencesDesc =>
      'Choose how you want to use the app. You can change this later.';

  @override
  String get onboardingFieldLanguage => 'Language';

  @override
  String get onboardingFieldCountry => 'Country';

  @override
  String get onboardingFieldCurrency => 'Main currency';

  @override
  String get onboardingCreateAccountTitle => 'Create your first account';

  @override
  String get onboardingCreateAccountDesc =>
      'Example: bank, cash, wallet. You can add more later.';

  @override
  String get onboardingFieldInitialBalance => 'Starting balance (optional)';

  @override
  String get onboardingHelperInitialBalance =>
      'If you\'re not sure, leave it blank.';

  @override
  String get onboardingErrorNoAccount =>
      'Create at least 1 account to continue.';

  @override
  String get onboardingCategoriesTitle => 'Choose your categories';

  @override
  String get onboardingCategoriesDesc =>
      'Keep what you use. You can change this later.';

  @override
  String get onboardingActionSelectAll => 'Select all';

  @override
  String get onboardingActionDeselectAll => 'Deselect all';

  @override
  String get catHousing => 'Housing (rent/fees)';

  @override
  String get catUtilities => 'Utilities (water, electricity, gas)';

  @override
  String get catInternet => 'Internet & phone';

  @override
  String get catGroceries => 'Groceries';

  @override
  String get catRestaurants => 'Restaurants';

  @override
  String get catTransport => 'Transport & Fuel';

  @override
  String get catFuel => 'Fuel';

  @override
  String get catCarMaintenance => 'Car Maintenance';

  @override
  String get catHealth => 'Health & Pharmacy';

  @override
  String get catPharmacy => 'Pharmacy';

  @override
  String get catEducation => 'Education';

  @override
  String get catCreditCard => 'Credit Card (Expenses)';

  @override
  String get catDebts => 'Loans';

  @override
  String get catFees => 'Fees & charges';

  @override
  String get catSubscriptions => 'Subscriptions (apps/streaming)';

  @override
  String get catPersonal => 'Personal care';

  @override
  String get catClothing => 'Clothing';

  @override
  String get catWork => 'Work (tools/services)';

  @override
  String get catTaxes => 'Taxes';

  @override
  String get voiceTitleExpense => 'Record expense';

  @override
  String get voiceTitleIncome => 'Record income';

  @override
  String get voiceTitleTransfer => 'Record transfer';

  @override
  String get voiceButtonType => 'Type';

  @override
  String get voiceStatusListening => 'Listening...';

  @override
  String get voiceStatusManual => 'Manual mode';

  @override
  String get voiceStatusWaiting => 'Waiting...';

  @override
  String get voiceTranscriptPlaceholder => 'Transcription will appear here';

  @override
  String get voicePermissionButton => 'Allow microphone';

  @override
  String get voiceChipAmount => 'Amount';

  @override
  String get voiceChipAccount => 'Account';

  @override
  String get voiceChipDate => 'Date';

  @override
  String get voiceChipCategory => 'Category';

  @override
  String get voicePromptAmount => 'Say the amount';

  @override
  String get voicePromptAccount => 'Which account is this from?';

  @override
  String get voicePromptDate => 'Was it today?';

  @override
  String get voicePromptCategory => 'Which category?';

  @override
  String get voiceAmountLabel => 'Enter the amount';

  @override
  String get voiceAccountLabel => 'Choose the account';

  @override
  String get voiceAccountAll => 'View all';

  @override
  String get voiceDateLabel => 'When was it?';

  @override
  String get voiceDateToday => 'Today';

  @override
  String get voiceDateYesterday => 'Yesterday';

  @override
  String get voiceDateOther => 'Another day';

  @override
  String get voiceCategoryLabel => 'Choose the category';

  @override
  String get voiceCategoryAll => 'View all';

  @override
  String get voiceCategoryUncategorized => 'Uncategorized (Other)';

  @override
  String get voiceConfirmTitle => 'Confirmation';

  @override
  String get voiceEditButton => 'Edit';

  @override
  String get voiceSavingLabel => 'Saving...';

  @override
  String get voiceSuccessLabel => 'Recorded';

  @override
  String get voicePrimaryContinue => 'Continue';

  @override
  String get voicePrimaryConfirm => 'Confirm';

  @override
  String get voicePrimarySaving => 'Saving';

  @override
  String get voicePrimaryNew => 'Record another';

  @override
  String get voiceSecondaryCancel => 'Cancel';

  @override
  String get voiceSecondaryClose => 'Close';

  @override
  String get voiceSnackbarMissingAccount => 'Select a source account';

  @override
  String get voiceSnackbarMissingDate => 'Select a date';

  @override
  String get voiceSnackbarMissingCategory => 'Select a category';

  @override
  String get voiceSnackbarInvalidAmount => 'Amount must be greater than 0';

  @override
  String get voiceSnackbarSaveError => 'Error saving';

  @override
  String get voiceSnackbarAmountRequired => 'Enter a valid amount';

  @override
  String get voiceSearchAccount => 'Search account';

  @override
  String get voiceSearchCategory => 'Search category';

  @override
  String get voiceErrorNotUnderstoodType =>
      'I didn\'t understand. You can type it.';

  @override
  String get voiceErrorRepeat => 'I didn\'t understand. Please repeat.';

  @override
  String get voiceErrorMicPermission => 'Microphone permission denied';

  @override
  String get voiceMultipleAccounts =>
      'I found more than one account. Tap to choose.';

  @override
  String get voiceMultipleCategories =>
      'I found more than one category. Tap to choose.';

  @override
  String get voiceNoAccounts => 'You don\'t have any accounts yet.';

  @override
  String get voiceNoCategories => 'You don\'t have any categories yet.';

  @override
  String voiceAccountsListTemplate(Object names) {
    return 'Your accounts are: $names.';
  }

  @override
  String voiceCategoriesListTemplate(Object names) {
    return 'The categories are: $names.';
  }

  @override
  String voiceConfirmPromptTemplate(Object summary) {
    return '$summary Say confirm or cancel.';
  }

  @override
  String get voiceEditPrompt => 'Ok. Edit the fields below.';

  @override
  String get voiceDateSelectPrompt => 'Ok. Choose the date below.';

  @override
  String get voiceConjunction => 'and';

  @override
  String voiceSummaryTemplate(
    Object account,
    Object amount,
    Object category,
    Object date,
  ) {
    return 'I\'ll record: $amount in $category, from account $account, $date.';
  }

  @override
  String get settingsVoiceAssistantTitle => 'Assistant voice';

  @override
  String get settingsVoiceAssistantDesc =>
      'Enable to hear voice prompts while recording.';

  @override
  String budgetsHeaderCompactExpenses(Object value) {
    return 'Planned expenses: $value';
  }

  @override
  String get budgetsSavePlanButton => 'Save plan';

  @override
  String get budgetsSavePlanMicrocopy =>
      'It only saves your plan. It doesn\'t move your money.';

  @override
  String get budgetsSavePlanSuccess => 'Plan saved';

  @override
  String get budgetsSummaryAffordTitle => 'Will I be okay this month?';

  @override
  String get budgetsStatusEnough => 'You’re okay';

  @override
  String get budgetsStatusNotEnough => 'Not enough';

  @override
  String get budgetsStatusJustRight => 'Right on track';

  @override
  String budgetsAmountLeftover(Object currency, Object amount) {
    return 'You have $currency $amount left';
  }

  @override
  String budgetsAmountShort(Object currency, Object amount) {
    return 'You’re short by $currency $amount';
  }

  @override
  String get budgetsAmountZero => 'You’re around zero';

  @override
  String get budgetsSummaryAffordOneLine => 'Income – Expenses – Debt payments';

  @override
  String get budgetsSummaryAffordCalming =>
      'This is just a plan. It doesn’t move your money.';

  @override
  String get budgetsCtaAdjust => 'Adjust my plan';

  @override
  String get budgetsCtaSaveGoal => 'Save leftover as a goal';

  @override
  String get budgetsCtaReview => 'Review my plan';

  @override
  String get budgetsSummaryBreakdownTitle => 'Where does this come from?';

  @override
  String get budgetsSummaryHelpTitle => 'To make it work';

  @override
  String budgetsHelpText(Object currency, Object amount) {
    return 'You’re short by $currency $amount. Reduce expenses or add income by that amount.';
  }

  @override
  String get budgetsHelpActionCategories => 'View categories';

  @override
  String get budgetsHelpActionIncome => 'Add income';

  @override
  String budgetsHeaderCompactIncomes(Object value) {
    return 'Planned income: $value';
  }

  @override
  String budgetsHeaderCompactBalance(Object value) {
    return 'Balance: $value';
  }

  @override
  String get budgetsActionAddRecord => 'Add to plan';

  @override
  String get budgetsModalTitle => 'Add to Plan';

  @override
  String get budgetsModalButtonAdd => 'Add';

  @override
  String get budgetsModalConfirmAdded => 'Added to plan';

  @override
  String get budgetsEntryDialogDeleteConfirm =>
      'Remove this entry from the plan?';

  @override
  String get budgetsEntryDialogDeleteAction => 'Yes, remove';

  @override
  String get budgetsStatusExceededChip => 'Exceeded';

  @override
  String budgetsStatusOverText(Object value) {
    return 'You went over by $value';
  }

  @override
  String get budgetsStatusLimitReached => 'Limit reached';

  @override
  String budgetsStatusRemainingText(Object value) {
    return 'You have $value left';
  }
}
